### ISSUE TITLE
Fan support for Commander Pro 

### ISSUE THREAD

**Issue by Eriobis** [Legion2/CorsairLightingProtocol#105]
**Describe the problem**
A clear and concise description of your problem.

I am setting the commander pro but there's no control for the fans, is this feature implemented yet ?

**Screenshots**
![image](https://user-images.githubusercontent.com/9793935/73113139-27d3a680-3ee0-11ea-95bb-668458da6378.png)

**System (please complete the following information):**
 - OS: Windows 10 
 - Board: Sparkfun Micro 5V
 - IDE: Arduino IDE
 - Version: 1.8.10
 - Sketch: CommanderPRO]

**Code changes**
Did you changed the code of the library or the sketch?
Nop

**Comment by Eriobis** [comment]
I have found how ... might be nice to have it in the wiki though !! I tought the feature wasn't implemented yet

**Comment by Legion2** [comment]
How did you solved the problem? If you are using the CommanderPRO sketch there should be 4 fans in iCUE.

**Comment by Legion2** [comment]
The Commander PRO has some limitations, I will document them in the sketch and Wiki #106

**Comment by Legion2** [comment]
@Eriobis I added some documentation in the [wiki](https://github.com/Legion2/CorsairLightingProtocol/wiki/Commander-PRO)
