### ISSUE TITLE
Wiring

### ISSUE THREAD

**Issue by eduardokum** [Legion2/CorsairLightingProtocol#107]
there is some documentation on how to connect the LED wires to control 6 fans on a lighting node pro channel and control them individually

I use a hub but it distributes only the changes of the first fan of the icue, as if all the fans were cloned from the first.

is there any way to connect them so that I can control them individually

I use sketch LightingNodePro on an arduino pro mini board with leonardo microcontroller

**Comment by Legion2** [comment]
What hub did you use? If you created the hub yourself, the fans should be in series, as you would connect multiple led strips in series. That's because the RGB control connector has four cables, 5V, In, Out, GND (In/Out may be swapped!). The Out singal should be connected to the In of the next fan.

**Comment by eduardokum** [comment]
i'm using this fan, Deepcool CF120

![Deepcool CF120](http://www.deepcool.com/ProductGallery/DEEPCOOL/Accessory/CF120_3IN1/Gallery/800X480/02.jpg)


with this hub, the come with the box, this one in the center
![This one in the middle](http://www.deepcool.com/ProductGallery/DEEPCOOL/Accessory/CF120_3IN1/Gallery/800X480/09.jpg)

Yes, I understand, but my deepcool cf120 fans only have 3 pins, 5v Data gnd, the LL fans from corsair also have an output signal pin that allows serial connection is that it?

**Comment by Legion2** [comment]
yes all Corsair fans have 4 pin RGB connectors

**Comment by Legion2** [comment]
I think your fan hub does not support to address individual fans.

**Comment by eduardokum** [comment]
Yes! I don’t know that! 

Thanks!

**Comment by skadzynski** [comment]
![20200127_052239](https://user-images.githubusercontent.com/44334614/73150223-8e65e980-40c5-11ea-8d02-8ea58f580e08.jpg)
 Hi
Meine Lüfter haben die Kontakte, was ist denn was?

**Comment by Legion2** [comment]
Sind das addressierbare LEDs? Welche Spannung brauchen die LEDs? Wenn es addressierbare LEDs sind und die Spannung 5v ist würde ich tippen, das außen die 5V und GND Anschlüsse sind. Und die Anschlüsse dazwischen sind in und out signal. Du musst das ausprobiere es sehr wahrscheinlich ausprobieren wenn du keine anderen Informationen über die Lüfter hast.

**Comment by skadzynski** [comment]
Ja sind Adresierbare, +,-,data in is klar aber das 4. Was unbeschriftet ist is un klar, wenn ich es als data out nehme wird der 2. Lüfter nicht gesteuert.

**Comment by skadzynski** [comment]
![20200127_090329](https://user-images.githubusercontent.com/44334614/73158373-ead80180-40e3-11ea-9a35-da32c79f8d3e.jpg)
 Das sind die, ich googel schon seid 2 Tagen 😉
Dein Projekt ist echt der hammer👍

**Comment by Legion2** [comment]
@skadzynski waren bei dem Lüfter irgendwelche Kabel und Adapter dabei? Vielleicht geben diese Aufschluss darauf was der vierte Anschluss macht.

**Comment by skadzynski** [comment]
![Screenshot_20200128-041510_Samsung Internet](https://user-images.githubusercontent.com/44334614/73232929-2ecf1300-4185-11ea-8951-e7ad44e860ff.jpg)
Nur der hub, fernbedienung und 6 pin Lüfter 
![Screenshot_20200128-041427_Samsung Internet](https://user-images.githubusercontent.com/44334614/73232961-4dcda500-4185-11ea-8dfa-eeba40b92cb1.jpg)

**Comment by robbo247** [comment]
hope this helps beenworkin on different 6 pin hubs the past few days,these
are the pinouts BUT if your making your own cables beware of the 12v

**Comment by Legion2** [comment]
@skadzynski did you use the 6pin connector to test the your fans? 

@robbo247 What is the pin out? Seems your message was broken.

**Comment by robbo247** [comment]
![original fan controller](https://user-images.githubusercontent.com/38098784/73260497-ed108d80-41c1-11ea-9ce5-dda6a69a6b2a.jpg)

**Comment by robbo247** [comment]
![replacement in square](https://user-images.githubusercontent.com/38098784/73260551-0580a800-41c2-11ea-82d9-fc715691ea9f.jpg)

**Comment by robbo247** [comment]
![PINOUT STRIP](https://user-images.githubusercontent.com/38098784/73260634-39f46400-41c2-11ea-934e-da842b62dae8.jpg)
![PIOUTS FAN](https://user-images.githubusercontent.com/38098784/73260635-3a8cfa80-41c2-11ea-901c-43ecfb913c19.jpg)

**Comment by skadzynski** [comment]
Ich werde meinen Controller auch mal zerlegen wenn ich Zeit finde, und dann berichten.
