### ISSUE TITLE
HW playback effect does not match preview

### ISSUE THREAD

**Issue by eduardokum** [Legion2/CorsairLightingProtocol#110]
**Describe the problem**
Hello, when I save effect on the hardware and close the icue it looks different, it seems that it doesn't persist

**Screenshots**
iCue Settings
![iCue Settings](https://i.imgur.com/yAtFH5D.png)

Preview settings when iCue is open
https://s5.gifyu.com/images/certo.gif

After I close iCue
https://s5.gifyu.com/images/errado.gif

 - OS: Windows 10
 - Board: Arduino Leonardo
 - IDE: Arduino IDE
 - Version: 0.10.0
 - Sketch: LightingNodePRO

sketch I'm using is: 
[LightingNodePRO](https://github.com/Legion2/CorsairLightingProtocol/blob/dev/examples/LightingNodePRO/LightingNodePRO.ino)

**Comment by Legion2** [comment]
This is a problem of the Rainbow channel effect, it should react to the size of the led strip, but iCUE does not provide this information. I will test this with a real Commander Pro but I think it has the same problem. So nothing I can fix in general. You can use other rainbow effect, they should look more similar to the preview.

**Comment by Legion2** [comment]
This also happens with a real ComPro, so it's a problem of Corsairs iCUE.

**Comment by Legion2** [comment]
You can change the library file so you get the effect you want. Change the end of line in the file [src/FastLEDController.cpp#L118](https://github.com/Legion2/CorsairLightingProtocol/blob/dev/src/FastLEDController.cpp#L118) from `-3 : 3` to `-15 : 15`. You can find the installed library in your Arduino Library folder.

**Comment by eduardokum** [comment]
> You can change the library file so you get the effect you want. Change the end of line in the file [src/FastLEDController.cpp#L118](https://github.com/Legion2/CorsairLightingProtocol/blob/dev/src/FastLEDController.cpp#L118) from `-3 : 3` to `-15 : 15`. You can find the installed library in your Arduino Library folder.

did it work, does it affect the other effects?

**Comment by Legion2** [comment]
@eduardokum this setting affects the Rainbow Channel and Rainbow Wave effect. 3 is the value of the Rainbow Channel and 15 for the Rainbow Wave effect.

**Comment by Legion2** [comment]
This Issue currently can't be fixed, as there is no mean in the Corsairs protocol to determine the type of connected device. So some effects can't be rendered correctly for some devices, e.g. Fans of different sizes. This Issue can also be reproduced with real Corsair LNP.
