### ISSUE TITLE
COM Port name

### ISSUE THREAD

**Issue by theorgBigBoss** [Legion2/CorsairLightingProtocol#113]
**Describe the problem**
Hi
My pro micro is burned and i bought new one
i connect new board to pc and its name show Arduino Leonardo
when i upload LNP sketch to the board and connect it its name change to USB Serial Device in device manager
how can i change to Arduino Leonardo or any name to show it in device manager?

**Screenshots**
https://imgur.com/NgAGf2k
https://imgur.com/PKDrLxB

**Comment by Legion2** [comment]
I think this name comes for a Windows usb driver, that is loaded for the device with the specific USB VID and PID. But when you upload the LNP sketch the USB VID and PID to corsair ones and corsair don't have driver for the COM port of a LNP, because LNP normally don't have a COM port.
