### ISSUE TITLE
Lighting Node CORE pin an löten

### ISSUE THREAD

**Issue by skadzynski** [Legion2/CorsairLightingProtocol#115]
Hi ich hab ein Lighting Node CORE
![IMG-20200310-WA0005](https://user-images.githubusercontent.com/44334614/76379359-28b97e00-6350-11ea-8bc1-2967b5036c32.jpeg)

Kann man eine pin leiste an löten 
![IMG-20200310-WA0009](https://user-images.githubusercontent.com/44334614/76379563-b09f8800-6350-11ea-8a62-0c58f5597215.jpeg)
Und so verbinden?
![HTNafYs](https://user-images.githubusercontent.com/44334614/76379688-0ecc6b00-6351-11ea-82ce-bf88b749ce9f.png)

**Comment by skadzynski** [comment]
![IMG-20200310-WA0007](https://user-images.githubusercontent.com/44334614/76379745-49ce9e80-6351-11ea-9bb4-bb3375be13f4.jpeg)

**Comment by Legion2** [comment]
@skadzynski ich verstehe nicht was du da anschließen willst, dem Wiring Diagramm zu folge möchtest du LED Lüfter anschließen. Aber die kann man doch an die anderen 6 Anschlüsse anschließen.

**Comment by skadzynski** [comment]
Das Bord hat doch drei unbedegte ausgänge

Ohne pins ich will den rgb hub an einen 
Lighting Node pro anschliesen, wenn es überhaupt geht.

**Comment by Legion2** [comment]
> Hi ich hab ein Lighting Node CORE

Auf dem Bild ist ein Fan Hub zu sehen.

Kannst du nochmal genau auflisten was du als Hardware hast, was du davon verbinden willst und was du damit erreichen willst. Bitte unterscheide dabei ob original Corsair Geräte und fake Corsair Geräte.

**Comment by skadzynski** [comment]
Ich hab den Lighting Node CORE original im gehäuse verbaut, da sind 3 sp rgb pro dran, hab noch nen 3er pack LL lüfter geholt und hab den rgb fun hub demontiert da ja bei dem 3er pack alles da bei ist, allerdings hab ich jetzt halt 2 verschiedene Lüfter an einem rgb fun hub,
Da dachte ich mir irgend wie muss ich doch den Lighting Node CORE aus dem pc gehäuse noch mit an den Lighting Node pro anschließen können.

**Comment by skadzynski** [comment]
Das sind alles original teile

**Comment by Legion2** [comment]
Den Lighting Node CORE kann man nicht mit einem Lighting Node pro verbinden. Beide brauchen eine USB connection. Du musst die Verschiedenen Lüfter typen mit verschiedenen Lighting Channels betreiben, der Lighting Node CORE hat nur einen Channel. Da du nur einen Fan Hub hast, kannst du auch nicht beide Lüfter typen über den Lighting Node pro betreiben.

**Comment by skadzynski** [comment]
![Screenshot_20200311-160840_Samsung Internet](https://user-images.githubusercontent.com/44334614/76431958-9a2a1880-63b2-11ea-8855-dfe0606e8301.jpg)
 Aber kann es sein das die pinout die gleichen sind wie beim pro

**Comment by Legion2** [comment]
Ja das kann schon sein, ich habe aber noch nicht in meinen CORE und PRO reingeschaut

**Comment by skadzynski** [comment]
Ah ok, hätte ja sein können.
Dank dir trotzdem.
