### ISSUE TITLE
Light Glitch

### ISSUE THREAD

**Issue by MajorLOLGaming** [Legion2/CorsairLightingProtocol#127]
**Describe the problem**
Light effects has some stutters and random colored flashes. (Only happens on the board using CLP)
I suspect this may be due to cable length or interference from the 6ish cables with 240v running in them.

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 10
 - Board: Leonardo Pro Micro
 - IDE: Arduino IDE
 - Version: 0.10.0
 - Sketch: LightingNodePRO

**Code changes**
Did you change the code of the library or the sketch?
No.

**Comment by MajorLOLGaming** [comment]
Maybe adding the string:
`#define FASTLED_ALLOW_INTERRUPTS 0`
would do some changes? (Source(s): [1](https://github.com/FastLED/FastLED/issues/306#issuecomment-219868579) [2](https://github.com/FastLED/FastLED/wiki/Interrupt-problems))
I will come back with an update as to if it worked.

**Comment by Legion2** [comment]
Which LED chipset are you using? I'm using WS2812B for one year now and have no problems.
When I had random light flashes, the LEDs were broken.

**Comment by MajorLOLGaming** [comment]
I am also using WS2812B, but when i use some other driver, it has no flashes.

**Comment by MajorLOLGaming** [comment]
im guessing a possible reason could also be poor connection between the board and leds? Or from power supply to leds?

**Comment by Legion2** [comment]
How do you power the LEDs?

**Comment by Legion2** [comment]
Did you connect GND of the Arduino with the GND on the power supply?

**Comment by MajorLOLGaming** [comment]
I power the leds from an 8 amp 5v psu, and i have a common ground between the leds and the board.

**Comment by MajorLOLGaming** [comment]
also, my leds are running off the psu, while the board is running on usb power

**Comment by MajorLOLGaming** [comment]
i will try and solder everything directly on it.

**Comment by MajorLOLGaming** [comment]
Hmm... I think the led data cables were just too long. It seems to have either been fixed, or stopped being so extreme.

**Comment by MajorLOLGaming** [comment]
Hmm... It's weird. Every time i try and mount it near my other cables, it start to flicker again...

**Comment by Legion2** [comment]
This doesn't sound like a problem with the implementation of this library.
