### ISSUE TITLE
LS100

### ISSUE THREAD

**Issue by skadzynski** [Legion2/CorsairLightingProtocol#150]
Hi
Ich Habe das problem das ich in icue bei dem ls100 wenn ich auf einem kanal nur ws2812b dran hab und auf RGBstreifen stelle das die sich nicht einzelnt steuern lassen, ist das normal?

**Comment by Legion2** [comment]
Wenn du in iCUE einen Effekt hinzufügst kannst du die LEDs einzeln anklicken und dadurch den effekt nur auf diese anwenden. Man kann auch mehrere LEDs für einen Effekt auswählen wenn man die Maus gedrückt hält während man einen größeren bereich auswählt. Falls das nicht verständlich ist, schau dir mal tutorials zu iCUE an, dort wird das im Video gezeigt.

**Comment by skadzynski** [comment]
Ja ich weiß  wie man makiert😉
Nur funktioniert es nicht wenn ich das mache, die leds gehen dann aus und ich kann dann nix mehr einstellen, erst wenn ich den Effekt wieder lösche und dann leuten beide langen streifen (27 ws2812b) gleich, sobald ich was markiere gehen sie aus.

**Comment by Legion2** [comment]
Welcher Version von CLP nutzt du und hast du was an dem Arduino sketch geändert?

**Comment by skadzynski** [comment]
Die aktuelle eigentlich, an der ino hab ich nur die RGB Reihenfolge geändert, wenn ich zu hause bin guck ich nach der genauen version.

**Comment by Legion2** [comment]
Welche iCUE version hast du? Ich verstehe das problem aktuell noch nicht, kannst du Screenshots machen damit ich das besser verstehe.

**Comment by skadzynski** [comment]
Ich weiß nicht was es war, hab es grad fotografieren wollen, und plötzlich funktioniert es.
Dann hat es sich ja geklärt, trotzdem danke.👍
