### ISSUE TITLE
Nexus bar

### ISSUE THREAD

**Issue by skadzynski** [Legion2/CorsairLightingProtocol#161]
Hi
Ob es möglich ist das corsair nexus Display nach zu bauen und über ein 3 5zoll Touch Display laufen zulassen?

**Comment by Legion2** [comment]
Ich hab da auch schon drüber nachgedacht, aber ich glaube dass die Nexus bar nicht das selbe USB Protokoll verwendet wie die LED Controller von Corsair. Denn die Nexus bar hat eigentlich nichts gemeinsam mit den LED Controllern und daher müsste man beim Reverse engineering von vorne beginnen und ohne selbst eine Nexus bar zu besitzen oder informationen über das USB Protokoll wird es schwierig diese nachzubauen.

**Comment by skadzynski** [comment]
Ok. Ich guck mal ob ich eine organisieren kann.

**Comment by theorgBigBoss** [comment]
Hi
i have this question too
but i dont undrestand your language

**Comment by Legion2** [comment]
@theorgBigBoss here a short translation:

@skadzynski ask if CLP can be used to build a NEXUS by yourself with a touch display.

I then responded that NEXUS probably use another USB protocol as it has nothing in common with the LED controllers. So to reverse engineer the NEXUS protocol I would need access to a NEXUS or at least have some basic information like USB PID.

@skadzynski tries to get one

**Comment by Legion2** [comment]
USB ids of iCUE NEXUS:
VID: `1b1c` 
PID: `1b8e`
