### ISSUE TITLE
Audio Reactive

### ISSUE THREAD

**Issue by satanisalive** [Legion2/CorsairLightingProtocol#162]
**Describe the problem**
When using the Audio Lighting in iCue, the lights show six different reactions, hard to explain. I want to use the whole strip, 2m 60LED/m, as one reaction. Again its hard to explain but hopefully the photo will explain.

**Screenshots**
![thumbnail_IMG_0876](https://user-images.githubusercontent.com/68960472/88818380-8db62900-d1b6-11ea-8914-9a4b7fefc86d.jpg)

**System (please complete the following information):**
 - OS: Windows 10
 - Board:. Arduino Leonardo
 - IDE: Arduino IDE
 - Version:  0.3.0
 - Sketch: [LightingNodePRO, RepeatAndScale]

**Code changes**
Did you changed the code of the library or the sketch?
I used the RepeatAndScale sketch to use my 120 WS2812b

**Comment by Legion2** [comment]
Yeah, using the scale functionality is the right approach here. I would recommend you to create a LS100 type device, which allow longer led strips (27 LEDs per strip) and then you simply scale that up to 120. So you only define 27 leds/1 LED strip in iCUE and then the Arduino scales that to 120 LEDs.
