### ISSUE TITLE
CorsairLightingProtocolHID' does not name a type; did you mean 'CorsairLightingProtocolSerial'?

### ISSUE THREAD

**Issue by TheAdminFrmoHell** [Legion2/CorsairLightingProtocol#167]
**Describe the problem**
Error compiling

**Screenshots**
https://pastebin.com/q8vEX2pD?fbclid=IwAR01ss11M-yhlZZCl9bquZ5z7j9MZdZ3WyDCoHGZBGMJp5IDL9gQ52kQUTk

**System (please complete the following information):**
Windows 10
 - Board: Pro Micro
 - IDE: Arduino IDE
 - Version: 1.8.13
 - Sketch: All of the example files

**Code changes**
Tried with both the original file and a file with changes.

**Comment by Legion2** [comment]
![image](https://user-images.githubusercontent.com/12752323/89833071-bb10b880-db60-11ea-8992-52d0119b8f61.png)
Did you select the CLP board?

**Comment by TheAdminFrmoHell** [comment]
I was just coming back here to write it was an above keyboard failure 😂
I had selected the Pro mini/micro, I've changed it to CLP and now it works perfectly
