### ISSUE TITLE
hoodloader2 with pi zero???

### ISSUE THREAD

**Issue by multidays** [Legion2/CorsairLightingProtocol#180]
hello is it possble to burn with a pi zero {isp}

**Comment by multidays** [comment]
i forgot to say i want to use a arduino uno  but i only have 1of those and 1 pi zero {raspberry pi}

**Comment by Legion2** [comment]
I don't know, this is a question related to [HoodLoader2](https://github.com/NicoHood/HoodLoader2) maybe there you find some information about it.
