### ISSUE TITLE
Ambient light (LS100) not regonized

### ISSUE THREAD

**Issue by Justdigit** [Legion2/CorsairLightingProtocol#184]
**Describe the problem**
When i flash Ambientbacklight sketch or LS100 its always regonized as Lightning node pro.
I have changed the Arduino Device ID but it wont change 

**System (please complete the following information):**
 - OS: WIN10
 - Board: Arduino Pro micro
 - IDE: [e.g. Arduino IDE]
 - Version: [e.g. 0.3.0]
 - Sketch: Ambientbacklight

**Comment by cjgun** [comment]
I did the same and everything worked out for me.
But I filled in the correct one first bootLoader from Leonardo.

Board: Arduino Pro micro
Sketch: Ambientbacklight

Tools — Boadr - CLP Arduino Leonardo
Device — LS100 Smart Lighting Controller

everything works as it should

**Comment by Legion2** [comment]
Did you select the correct device?
![image](https://user-images.githubusercontent.com/12752323/92807221-f8b06d80-f3ba-11ea-8c12-8444a82c5dfe.png)

**Comment by Justdigit** [comment]
Who wants to give me a hammer??

Works fine..... Just have to rescale the leds to my stripcount. Going to dive in this evening.

Thanks.
