### ISSUE TITLE
ATTiny85 Support

### ISSUE THREAD

**Issue by LuckyMallari** [Legion2/CorsairLightingProtocol#186]
Do you have any plans to support **[ATTiny85](https://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-2586-AVR-8-bit-Microcontroller-ATtiny25-ATtiny45-ATtiny85_Datasheet.pdf)**? I tried to setup a Leonardo as a composite device to have multiple channels. Got it working but the leo simply is not powerful enough esp with the limited memory. My goal is to have 20 independent channels. With your code, this is possible with 10 separate devices emulating Node pro (2 channels each). But an ATTiny85 approach is many times less expensive. 

So now, the route I'm planning to take is to have several ATTiny85 chips instead, with optionally another board as a USB host (as a generic USB hub if cheaper).

**Comment by Legion2** [comment]
The ATTiny85 doesn't support usb hid/it has no native usb support.

**Comment by Legion2** [comment]
But the CLP library is modular so you can split the usb part from the led controller.

**Comment by LuckyMallari** [comment]
> The ATTiny85 doesn't support usb hid/it has no native usb support.

V-USB runs well on the Attiny chip

**Comment by Legion2** [comment]
Is V-USB available as arduino library?

**Comment by Legion2** [comment]
>  I tried to setup a Leonardo as a composite device to have multiple channels. Got it working but the leo simply is not powerful enough esp with the limited memory.

@LuckyMallari Do you mean you have got it working to report more than one device in iCUE on a Leonardo?
