### ISSUE TITLE
I only can use Lightning node pro... 

### ISSUE THREAD

**Issue by ZeddBlock** [Legion2/CorsairLightingProtocol#188]
Hey !

First at all, forgive my english.
I'm using an arduino Micro (32u4). I tried this with the Lightning Node Pro, and everything work fine in Icue. 
But, when I choose LT100 ou LS100, my Arduino is still recognize as Nightning Node Pro... 

How to do ? Anyone else had this issue ?

**Comment by cjgun** [comment]
> Hey !
> 
> First at all, forgive my english.
> I'm using an arduino Micro (32u4). I tried this with the Lightning Node Pro, and everything work fine in Icue.
> But, when I choose LT100 ou LS100, my Arduino is still recognize as Nightning Node Pro...
> 
> How to do ? Anyone else had this issue ?

Choose LS100 instead of Node Pro when choosing a board model.
Tools- Devices - LS100
I have the same scarf and everything works fine.

**Comment by ZeddBlock** [comment]
Thank you so much ! It works. I just choosed it on exmaple. 
Have a nice day ;-)
