### ISSUE TITLE
More than 2 channels

### ISSUE THREAD

**Issue by dbobok** [Legion2/CorsairLightingProtocol#19]
Hello,

Is it possible to configure for more than 2 channels in 1 device?  I saw that we can define CHANNEL_NUM in LedController.h.  If I set it to let say 3 channels and modify LightingNodePRO.ino to add the extra channel, will it work? 
Thank you.

**Comment by Legion2** [comment]
No, the number of channels is limited by Corsair, because the official LNP has only two channels.
You can increase `CHANNEL_NUM`, but iCUE can only control the first two channels.
