### ISSUE TITLE
CorsairLightingProtocolHID does not name a type

### ISSUE THREAD

**Issue by Attack44** [Legion2/CorsairLightingProtocol#193]
**Describe the problem**
I have a problem with the examples 'LS100' or 'Ambient backlight', the error "CorsairLightingProtocolHID does not a name a type; did you mean CorsairLightingProtocolSerial?"

If I change it to 'CorsairLightingProtocolSerial', the check goes through without errors.

**Screenshots**
![error](https://user-images.githubusercontent.com/19206966/94570407-1d3b8f00-026f-11eb-8824-9991ec85d22f.PNG)

**System (please complete the following information):**
 - OS: Windows 10x64 (2004)
 - Board: Adafruit Metro mini
 - IDE: Arduino IDE 
 - Version: 1.8.13
 - Sketch: LS100 / Ambient backlight

**Comment by Legion2** [comment]
The Adafruit Metro mini uses a ATmega328 chip, which is not supported because it has no native USB capabilities.
