### ISSUE TITLE
Is it possible to switch an output on Pro Micro based on temperatures?

### ISSUE THREAD

**Issue by Alekky09** [Legion2/CorsairLightingProtocol#199]
Hello, is it possible to switch a random output based on the temps read by iCUE software?
I'm looking to control my leds with a Pro Micro and this library, but also switch a relay on/off based on a specific temp threshold.

**Comment by Legion2** [comment]
Use the CommanderPRO sketch which can be configured in iCUE as Commander PRO. It allows to receive temperature for fans, so you have to configure a fan and then can select the temperature source in iCUE.
