### ISSUE TITLE
Support Commander PRO Features

### ISSUE THREAD

**Issue by Legion2** [Legion2/CorsairLightingProtocol#20]
Make it possible to create a  Commander PRO with this library, so the the protocol is fully implemented.
Features that a Commander PRO have in addition to that of a LNP:
- [x] temperature sensors
- [x] voltage measurement
- [x] fan control
- [x] fan speed sensor

**Comment by mountaser** [comment]
that would be dope i was actually going to suggest it!

**Comment by Legion2** [comment]
@mountaser do you have hardware to test #21? Temperature- and Fan-Controller must be tested.

**Comment by TylerSeiford** [comment]
@Legion2 I have a pro micro, what exactly do you want tested?

I don't believe I have a method for temperature input to the arduino but I can test fan outputs.

**Comment by Legion2** [comment]
You can not power the fans directly from the arduino, the arduino only provides the pwm signal, so you need some wiring to use the arduino as fan controller.
For temperature all sensors that are compatible with most mainboards temperature connectors are supported, these sensors are NTC Thermistor 10 KOhms. They require a 10 KOhms resistor in series and then you measure the voltage between them.

A Commander PRO is more complex than a LNP.

**Comment by mountaser** [comment]
@Legion2  i can test fan control speed i have ML fans i can use them to test 
Don't have any temp sensors tho

**Comment by Legion2** [comment]
Ok, currently only fixed % power is supported by the fan controller. I will also implement fan curve support, but without measuring the fan speed.

**Comment by mountaser** [comment]
@Legion2 i can test anything for u 
Currently not at home spending time with some family but i can when i get back
Do u have telegram discord or anyway of communicating? 
My telegram is @mountaser_halak and my discord is mountaser #8924

**Comment by Legion2** [comment]
@mountaser Discord: Legion#8743

**Comment by Legion2** [comment]
PR is merged, this feature is in the next release.
