### ISSUE TITLE
LT100 more leds in two towers

### ISSUE THREAD

**Issue by kdbhu** [Legion2/CorsairLightingProtocol#200]
Hi!
I tried use the library and evrthing was good.
I use my sparkfun pro micro as LT100 device.
I want only 2 tower and more leds in each tower.
Can u help me?

**Comment by Legion2** [comment]
For iCUE the number of LEDs per tower is fixed, so you have to configure the number of LEDs for 2 towers. You can then scale the two towers using the `scaleSegments` function to whatever number you like, see https://github.com/Legion2/CorsairLightingProtocol/wiki/Scale-separate-segments-of-a-channel.

**Comment by kdbhu** [comment]
Thanks for help. I will try it.

**Comment by kdbhu** [comment]
Sorry i'm not very good at english can u send me a example code?

**Comment by kdbhu** [comment]
> For iCUE the number of LEDs per tower is fixed, so you have to configure the number of LEDs for 2 towers. You can then scale the two towers using the `scaleSegments` function to whatever number you like, see https://github.com/Legion2/CorsairLightingProtocol/wiki/Scale-separate-segments-of-a-channel.

**Comment by kdbhu** [comment]
So I have to define 2*27 leds?
Can u help in private?

**Comment by Legion2** [comment]
the following code make the towers using 50 LEDs.
```c++
ledController.onUpdateHook(0, []() {
  CLP::SegmentScaling segments[2] = {{27, 50}, {27, 50}};
  CLP::scaleSegments(&ledController, 0, segments, 2);
});
```
Here is an example how the onUpdateHook should be used https://github.com/Legion2/CorsairLightingProtocol/blob/dev/examples/RepeatAndScale/RepeatAndScale.ino

Also make sure `CRGB ledsChannel1[100];` has enough LEDs (50 + 50) or whatever number you need.

I can give more specific answers if you provide more information.

**Comment by kdbhu** [comment]
Thank you! that's work very well.

**Comment by Legion2** [comment]
change `ledController.addLEDs(0, ledsChannel1, 100)` to `ledController.addLEDs(0, ledsChannel1, 54)`

**Comment by kdbhu** [comment]
So fixed it, but thanks for a lot of help!
I need zo change the value of ledControllers led.

`ledController.addLEDs(0, ledsChannel1, 54);`
