### ISSUE TITLE
CorsairLightingProtocolHID error

### ISSUE THREAD

**Issue by Wiedenhoferkilian** [Legion2/CorsairLightingProtocol#201]
I want to upload the LightningNodePRO sketch to my arduino nano. ( I have already tried to use an arduino uno). I installed the libraries and the all work but when i want to upload the sketch i get this error:

In file included from C:\Users\Kilian\Documents\Arduino\libraries\Corsair_Lighting_Protocol\src/FastLEDController.h:18:0,
                 from C:\Users\Kilian\Documents\Arduino\libraries\Corsair_Lighting_Protocol\src/CorsairLightingProtocol.h:31,
                 from C:\Users\Kilian\AppData\Local\Temp\Temp1_Corsair_Lighting_Protocol-0.14.2.zip\Corsair_Lighting_Protocol-0.14.2\examples\LightingNodePRO\LightingNodePRO.ino:16:
C:\Users\Kilian\Documents\Arduino\libraries\FastLED/FastLED.h:14:21: note: #pragma message: FastLED version 3.003.003
 #    pragma message "FastLED version 3.003.003"
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
LightingNodePRO:28:1: error: 'CorsairLightingProtocolHID' does not name a type; did you mean 'CorsairLightingProtocolSerial'?
 CorsairLightingProtocolHID cHID(&cLP);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~
 CorsairLightingProtocolSerial
C:\Users\Kilian\AppData\Local\Temp\Temp1_Corsair_Lighting_Protocol-0.14.2.zip\Corsair_Lighting_Protocol-0.14.2\examples\LightingNodePRO\LightingNodePRO.ino: In function 'void loop()':
LightingNodePRO:38:2: error: 'cHID' was not declared in this scope
  cHID.update();
  ^~~~
C:\Users\Kilian\AppData\Local\Temp\Temp1_Corsair_Lighting_Protocol-0.14.2.zip\Corsair_Lighting_Protocol-0.14.2\examples\LightingNodePRO\LightingNodePRO.ino:38:2: note: suggested alternative: 'HI1'
  cHID.update();
  ^~~~
  HI1
exit status 1
'CorsairLightingProtocolHID' does not name a type; did you mean 'CorsairLightingProtocolSerial'?

Can pls someone help me?
I use the newest version of the Arduino IDE

Thanks!!

**Comment by Legion2** [comment]
Arduino Nano is not supported, because of hardware limitation, see the Readme
