### ISSUE TITLE
Control rgb with iCue and Fans with external program

### ISSUE THREAD

**Issue by Hungermatt** [Legion2/CorsairLightingProtocol#207]
Hi,

I am new here, so I would first like to thank you for this interesting project.

I am trying to run a small project with this as the basis. My aim is to control the fans using a program external to iCue. I've noticed that with Lighting Node PRO it doesn't work and I'm wondering if I have to use Commander PRO to do this.

Thank you for your help

System
 - OS: Windows 10
 - Board: Arduino Micro
 - Device: Lighting Node PRO
 - Version of IDE: Arduino IDE 1.8.1
 - Version of CLP: 0.14.2]
 - Version of CLP Boards: 0.2.0
 - Sketch: LightingNorePRO

**Comment by Legion2** [comment]
Only Commander PRO supports Fan control. But if you use Commander PRO iCUE will control the fans.
