### ISSUE TITLE
Commander Pro customization

### ISSUE THREAD

**Issue by kostyamat** [Legion2/CorsairLightingProtocol#212]
Hello.
Thanks a lot for your work. I was very interested in this project.
I would like to ask a few questions, if possible.
* Is it possible to create a custom fan type with more LEDs than official fans from Corsair? For example, my fans have 24 LEDs, and I do not see an opportunity to distribute them in the correct way so that the overall light scene is not disturbed. Because there is nothing similar in the possible options in the program. The program includes only tape segments 10 LEDs, 20 and fans 1, 4, 8, 12, 16, 36.

The rest of the questions will depend on the answer to this question.

**Comment by Legion2** [comment]
Yes, see https://github.com/Legion2/CorsairLightingProtocol/wiki/Scale-separate-segments-of-a-channel, you can define the fans as segments and the scale them to the size you want.
