### ISSUE TITLE
Pro Micro Hardware Lighting Bug

### ISSUE THREAD

**Issue by LiftKid** [Legion2/CorsairLightingProtocol#213]
**Describe the bug**
When using and arduino Pro Micro clone, hardware lighting will not work.

**To Reproduce**
Upload the code to a Pro Micro sparkfun clone (https://bit.ly/3pu6ya4) and try to set a hardware lighting setup in icue. It will just do a random effect or turn off. I have tried on two boards with two programs and both were buggy. For example, my friends board running the lighting node pro sketch just turned off the LEDs for hardware lighting whereas my board running the LS100 sketch will just be set to white instead of my set hardware lighting mode.

**Expected behavior**
I expected the LEDs to switch to the set hardware lighting mode.

**Screenshots**
I dont have any.

**System (please complete the following information):**
 - OS: Windows 10
 - Board: Sparkfun Pro Micro Clone (https://bit.ly/3pu6ya4)
 - Device: LS100 and Lighting Node Pro
 - Version of IDE: 1.8.13
 - Version of CLP: 0.14.1
 - Version of CLP Boards: 0.3.0
 - Sketch: LS100 and Lighting Node Pro

**Code changes**
None

**Comment by Legion2** [comment]
@LiftKid Can you make a screenshot of your hardware lighting config in iCUE.

**Comment by LiftKid** [comment]
> @LiftKid Can you make a screenshot of your hardware lighting config in iCUE.

![hw lighting](https://user-images.githubusercontent.com/77021733/107991388-6e55e080-6fce-11eb-9b19-61b41fa2d755.JPG)

**Comment by Legion2** [comment]
You know that with the LS100 the channels in iCUE are interchanged, so Channel 1 is Channel 2? Have you set the hardware lighting for the correct channel?

**Comment by LiftKid** [comment]
Yeah its definitely set correct because the preview works.

**Comment by Legion2** [comment]
can you try and use the latest version of the CLP library (0.14.2)

**Comment by LiftKid** [comment]
I updated to that library and re flashed the arduino. It still gets stuck in white instead of switching to hardware lighting.

**Comment by Legion2** [comment]
You use the LS100 sketch without any code changes?

**Comment by LiftKid** [comment]
Yeah I just load it straight from the examples page.

**Comment by Legion2** [comment]
So when you close/stop iCUE, the arduino goes into hardware lighting mode, but the lighting effect is not the one you configured in iCUE before?

**Comment by LiftKid** [comment]
If I use task manager to force close Icue the strips stay white and then turn off after 30 seconds. But if I shut my computer down they just stay white and never shut down. Just to make sure however I will try leaving my computer off for a minute to see if they eventually turn off.

**Comment by Legion2** [comment]
> turn off after 30 seconds

this is the hardware lighting mode timeout, when the arduino gets no command from iCUE in 30 seconds it switches into the hardware lighting mode

**Comment by LiftKid** [comment]
Yeah. It does seem that it's able to get into hardware lighting mode, just not during shutdown. I turned off my computer for 1 minute and it did not have the same effect as closing icue forcefully. (when it should)

**Comment by Legion2** [comment]
what iCUE version do you use?

**Comment by LiftKid** [comment]
3.37.140, the newest.

**Comment by Legion2** [comment]
I think this is then a problem of iCUE. I have also this version of iCUE, but my devices go into the correct hardware lighting mode when I stop iCUE.

**Comment by LiftKid** [comment]
Ok thanks, I hope that it will just eventually fix itself.
