### ISSUE TITLE
Build with VS Code and PlatformIO

### ISSUE THREAD

**Issue by thilbig** [Legion2/CorsairLightingProtocol#216]
Hi,
I open the project with VS Code and PlatformIO PlugIn. I can compile and upload it to my Arduino Leonardo. But the device isn't shown in iCUE software.
When I build it with ArduinoIDE then all works as described. Is it possible to port it to PlatformIO ? It's more easier to use with VS Code and PlatformIO than in ArduinoIDE.

**Comment by Legion2** [comment]
I don't know how to support the custom device setting which can be done in arduino IDE using the boards definition

**Comment by thilbig** [comment]
OK. Then I will give it a try and when it works I will do a pull request. Is that ok for you?

**Comment by Legion2** [comment]
Yes, pull requests are welcome.

**Comment by zastrixarundell** [comment]
I'll see to make a PR for the README but here's the required PlatformIO thing needed:
```ini
[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board_build.core = earlephilhower
board = pico
framework = arduino
build_flags = -DUSE_TINYUSB
upload_protocol = picotool
lib_deps =
	legion2/Corsair Lighting Protocol@^0.15.0
	adafruit/Adafruit TinyUSB Library@^2.2.6
```

Successfully built on my PC (which wouldn't otherwise) and uploaded on an unofficial board. 

Edit: example repo: https://github.com/zastrixarundell/corsair-rp2040-platformio
