### ISSUE TITLE
Corsair LL fan connect

### ISSUE THREAD

**Issue by MinadaLakmira** [Legion2/CorsairLightingProtocol#217]
how to connect 3 separate Corsair ll Fans with Lighting  Node Core

**Comment by Legion2** [comment]
Have a look at this example https://github.com/Legion2/CorsairLightingProtocol/blob/dev/examples/MultipleFans/MultipleFans.ino

It configures 6 fans on the first channel, and you can configure the number of leds per fan. If you want to use Lighting Node Core you have to change line https://github.com/Legion2/CorsairLightingProtocol/blob/dev/examples/MultipleFans/MultipleFans.ino#L32 and remove the second lighting channel. The sketch only handles lighting, for fan control and power supply you need additional hardware.
