### ISSUE TITLE
CorsairLightingProtocol/examples/MultipleFans/MultipleFans.ino Error 

### ISSUE THREAD

**Issue by MinadaLakmira** [Legion2/CorsairLightingProtocol#218]
CorsairLightingProtocol/examples/MultipleFans/MultipleFans.ino

This Code only control 8 leds on Corsair LL, How to setup it for all 16 leds ?

**Comment by robbo247** [comment]
i dont know if it works the same but you can edit the number of leds in the
ino file directly then upload it too your arduino

**Comment by Legion2** [comment]
@MinadaLakmira you have to change the line `#define NUMBER_OF_LEDS_PER_FAN 8` to 16

**Comment by MinadaLakmira** [comment]
No problem, I found the answer 👍👍-------- Original message --------From: Robbo247 <notifications@github.com>Date: Mon, 8 Mar 2021, 11:59To: Legion2/CorsairLightingProtocol <CorsairLightingProtocol@noreply.github.com>Cc: MinadaLakmira <pminadalakmiragaming@gmail.com>, Author <author@noreply.github.com>Subject: Re: [Legion2/CorsairLightingProtocol] CorsairLightingProtocol/examples/MultipleFans/MultipleFans.ino Error  (#218)

i dont know if it works the same but you can edit the number of leds in the

ino file directly then upload it too your arduino

**Comment by robbo247** [comment]
Are people actually using corsairs fans etc on this project just too bypass
a genuine node etc ,i thought this project was aimed more as a custom non
brand lighting workaround
