### ISSUE TITLE
Arduino Micro support

### ISSUE THREAD

**Issue by phrost401** [Legion2/CorsairLightingProtocol#219]
I see that it says that the Arduino Micro is supported however in the CLP boards I don't see this as a choice. Any suggestions would be great, if I got to return it and get another that's fine too. I've tried compiling and uploading while selecting Arduino Leonardo and it comes up in device manager with an ! saying that the device failed to start. 

Thanks in advance.

**Comment by Legion2** [comment]
Sorry, I totally forgot about this one, I released a new version of the boards which add support for arduino micro https://github.com/Legion2/CorsairLightingProtocolBoards/releases/tag/avr-0.3.1
