### ISSUE TITLE
Support for fans with different led count

### ISSUE THREAD

**Issue by Vincent1638** [Legion2/CorsairLightingProtocol#22]
Is there a way to change the number of led per fan so that the animation would work correctly with fans with less leds.

**Comment by Legion2** [comment]
> led per fan

What did you mean by this, which fans with leds do you use?
I think you can configure the leds per fan in iCUE, there are "HD RGB fan" (12 leds), "SP RGB fan" (1 led), "LL RGB fan" (16 leds) and "ML RGB fan" (4 leds) you can select.
If you want animations only for let's say 8 leds you can configure one RGB Strip(10 leds) and then select only the first 8 leds for the animation in iCUE.

**Comment by Legion2** [comment]
@Vincent1638 Did I answer your question or misunderstood something?
