### ISSUE TITLE
Separate fan control from arduino

### ISSUE THREAD

**Issue by denynic96** [Legion2/CorsairLightingProtocol#223]
hello, 

I would like to separate the fan control from the arduino and offload it to another chip, but I'm having problems finding the fan data sent by icue. My idea was to use a emc2305 to control the fans, and I suspect (correct me if I'm wrong) that the data from icue is received by the arduino and then the simplefancontroller generates the pwm signal. Is it possible to expose the variable with the fan speed to send it through I2C? This way I wouldn't need the simplefancontroller library and get better control plus fan failure detection. 

I'm using a arduino pro micro clone (based on leonardo)
and simulating a commander pro

love your work and thanks alot
Regards

**Comment by Legion2** [comment]
The simple fan controller is only an example implementation, you can implement your own fan controller by inheriting from the `FanController` abstract class. You can find documentation [here](https://legion2.github.io/CorsairLightingProtocol/classFanController.html).
