### ISSUE TITLE
is Arduino bord is limited to one Lighting Node Pro ? 😕

### ISSUE THREAD

**Issue by MinadaLakmira** [Legion2/CorsairLightingProtocol#226]
Can I use one Arduino as multiple Lighting Node pro or Connect more than 2 channels on Lighting Node pro ?

**Comment by Legion2** [comment]
Only one Lighting Node pro on one arduino with two channels, but you can map the channels to multiple LED strips

**Comment by MinadaLakmira** [comment]
> Only one Lighting Node pro on one arduino with two channels, but you can map the channels to multiple LED strips

But, How

**Comment by Legion2** [comment]
[Here](https://github.com/Legion2/CorsairLightingProtocol/blob/dev/examples/MultipleFans/MultipleFans.ino) is an example where one LED channel is mapped to six LED fans with different LED strips. You can change the number of LEDs for each individual LED strips and map to a different number using the `FastLED.addLeds` function.
