### ISSUE TITLE
Support Teensy 4.0/4.1

### ISSUE THREAD

**Issue by blazini36** [Legion2/CorsairLightingProtocol#227]
**Describe the problem**
Support Teensy 4.x

Just opening an issue to request support for a Teensy 4.x. I whipped up a PCB for Teensy4  for similar capabillties to a Commander Pro based on this project [https://mstrthealias.gitbook.io/teensy-fan-controller/build-instructions/firmware](url). I got that firmware running on a Teensy4  (was pretty difficult) but I was never able to get the UI running for configuration. It'd be great to get this Arduino implementation going on the Teensy, but I can't write code to save my life.

![20210214_161425](https://user-images.githubusercontent.com/41092666/114282489-4012e100-9a12-11eb-943f-9b599f2a0914.png)

**Comment by Legion2** [comment]
Sorry, but the developer of Teensy denied (deleted) my request to provide a better API. So, without that API I'm not able to support the Tennsy boards, see https://github.com/Legion2/CorsairLightingProtocol/issues/97#issuecomment-701224443.
