### ISSUE TITLE
icue rgb fan

### ISSUE THREAD

**Issue by MerlijnMoonen** [Legion2/CorsairLightingProtocol#230]
Sorry if this is wrong but i'm not good at github.  Can you also select a rgb fan in icue or only a rgb strip?

Merlijn Moonen

**Comment by Legion2** [comment]
@MerlijnMoonen You can also select RGB fans in iCUE. However, on a channel you can not mix RGB strips with RGB fans. So you would use one channel for fans and the other channel for strips.

**Comment by MerlijnMoonen** [comment]
Thanks
