### ISSUE TITLE
How Do i wire commander pro using this CorsairLightingProtocol

### ISSUE THREAD

**Issue by jiveshd83** [Legion2/CorsairLightingProtocol#233]
I am having some problem how to wire for commander pro and where does fans will go, where will leds, where will temperature sensor i am having a lot of trouble in it

**Comment by Legion2** [comment]
In the `CommanderPRO.ino` you can see which pins are used. In the [Wiki](https://github.com/Legion2/CorsairLightingProtocol/wiki/Commander-PRO) you can find more information. However, to control fans and temperature sensors, additional components are required. The hardware wiring is out of scope of this project, you can find more information about PWM fans and temperature sensors in the internet.

**Comment by jiveshd83** [comment]
ok so you mean only i can control the pwm and not be able to monitor them, Also tell me for thermal sensor where will go positive and where will negative

**Comment by jiveshd83** [comment]
and what additional components are required?

**Comment by jiveshd83** [comment]
Thanks Brother Lots of love From India ❤❤
