### ISSUE TITLE
Losting connection

### ISSUE THREAD

**Issue by yoann56100** [Legion2/CorsairLightingProtocol#236]
im using an arduino pro micro to control 3 120mm LL fans and a ws2812b strip at the beginning it work perfectly but now its loosing connection after few minutes... i dont know why, i changed nothing

**Comment by Legion2** [comment]
please provide more information and use the use the [bug report template](https://github.com/Legion2/CorsairLightingProtocol/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md)
