### ISSUE TITLE
Increase brightness of LS100

### ISSUE THREAD

**Issue by aaronkim98** [Legion2/CorsairLightingProtocol#240]
Hi, I was just wondering if the increased brightness mod/fix you have implemented for the Corsair LS100s can be used directly with iCUE? I don't have an arduino atm, but I do have LS100s and they are quite dim. Can't seem to find any info about how to force them to be 100% any other way. Cheers

**Comment by Legion2** [comment]
Sorry, but the increased brightness is a software post processing effect which is applied by this library to the RGB values received from iCUE, without this library and an arduino the effect can not be applied.

**Comment by aaronkim98** [comment]
Ah no worries, thanks so much for the explanation! :)
