### ISSUE TITLE
LS100

### ISSUE THREAD

**Issue by Oxygene666** [Legion2/CorsairLightingProtocol#242]
Hello there ,

I am running a 49 inch monitor and did install LS100 Module with single monitor mode as in your example. 
I managed to scale my leds accordingly and everything is ok

But ...

The module is capturing the whole screen meaning most of the time the videos are not full screen ( for example youtube or Netflix ) and therefor only part of the screen is captured 

Is there any way to change the screen capture area ?

**Comment by Legion2** [comment]
The screen capturing is done by iCUE and I'm not a developer of iCUE. Currently iCUE does not support selecting a different screen area. However if the video is full screen and has black bars, iCUE should detect this and show the colors without the black bars.
Please notice that the copyright protection of some video on demand providers prevent iCUE from capturing the screen.
