### ISSUE TITLE
LT100

### ISSUE THREAD

**Issue by Oxygene666** [Legion2/CorsairLightingProtocol#244]
Hello 

I have sucessfully made a LT100 , but there is a firmware on ICUE 4 . It cant update . Is there any way to do the update ?

Thx

**Describe the problem**
A clear and concise description of your problem.

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Board: [e.g. Arduino Leonardo]
 - Device: [e.g. Lighting Node PRO]
 - Version of IDE: [e.g. Arduino IDE 1.8.13]
 - Version of CLP: [e.g. 0.14.2]
 - Version of CLP Boards: [e.g. 0.2.0]
 - Sketch: [e.g. RepeatAndScale]

**Code changes**
Did you changed the code of the library or the sketch?

**Comment by Legion2** [comment]
You should ignore the updates displayed in iCUE, because this library uses its own custom firmware, so you can not use the update from iCUE.
