### ISSUE TITLE
Pi Pico Support

### ISSUE THREAD

**Issue by WanaGo** [Legion2/CorsairLightingProtocol#246]
Hello,

What are the chances that this can be ported or made to work on the Raspberry Pi Pico, with the aim of trying to get support for more than 2 channels. 
Thinking along the lines of the Razer Chroma which can support 6 channels.
It has an Arduino core for it, just wondering if it might be a potential candidate?

Thanks

**Comment by Spegs21** [comment]
Should be functional with Legion2/CorsairLightingProtocol#215. I've compiled it and flash it but haven't hooked up a fan yet.

**Comment by WanaGo** [comment]
> Should be functional with #215. I've compiled it and flash it to a Pico but haven't hooked up a fan yet.

Nice - But Fan, or Lights, do you mean?

**Comment by Spegs21** [comment]
I've compiled the Lighting Node Pro sketch for the Pico and flashed it. Lighting Node Pro is lights only. I haven't tried one that incorporates a fan controller. The new Readme from the PR has instructions to do this. So at least lights should work.

**Comment by WanaGo** [comment]
> I've compiled the Lighting Node Pro sketch for the Pico and flashed it. Lighting Node Pro is lights only. I haven't tried one that incorporates a fan controller. The new Readme from the PR has instructions to do this. So at least lights should work.

Cool, yep you just mentioned you haven't hooked a fan up yet, I was wondering if that was a typo and you actually meant you hadnt hooked any lights up yet. Lights only is what I thought too, hence the question about Fans.

**Comment by cnn123666** [comment]
> 我已经为 Pico 编译了 Lighting Node Pro 草图并将其闪烁。Lighting Node Pro 只有灯光。我还没有尝试过包含风扇控制器的产品。PR 的新自述文件有执行此操作的说明。所以至少灯光应该可以工作。

How to use other devices such as LS100

**Comment by cnn123666** [comment]
> 我已经为 Pico 编译了 Lighting Node Pro 草图并将其闪烁。Lighting Node Pro 只有灯光。我还没有尝试过包含风扇控制器的产品。PR 的新自述文件有执行此操作的说明。所以至少灯光应该可以工作。

Hello, I'm sorry that my English is not very good. I have successfully uploaded TinyUSB sketch to Pico according to your tutorial, and ICUE has successfully identified it, but the lighting channel seems to be abnormal and some of it is stuck.

**Comment by Spegs21** [comment]
@cnn123666 Did you modify the sketch for the number of LEDs you are running on the channel? It's set to 96 as an example but this needs to match your specific setup.

**Comment by cnn123666** [comment]
@Spegs21 I didn't change the sketch, the refresh rate of the lighting channel is wrong, it seems to be only 15FPS, but the hardware channel is fine

**Comment by cnn123666** [comment]
https://user-images.githubusercontent.com/52467395/151735897-6c82bd93-72e6-4463-8bd3-604aedd7eb96.mp4

**Comment by Spegs21** [comment]
@cnn123666 Thanks for the video. When you say the hardware channels is fine what do you mean?

**Comment by cnn123666** [comment]
@Spegs21 When ICUE is turned off, the light refresh rate is normal

**Comment by cnn123666** [comment]
https://user-images.githubusercontent.com/52467395/151973000-1233277b-9ca8-4e8c-a6c5-058de0a4c649.mp4


https://user-images.githubusercontent.com/52467395/151973007-9578073b-f71e-4e1a-ad79-ddf0118fa3ea.mp4

**Comment by Spegs21** [comment]
@cnn123666 Ok, that makes sense. I only have a spare half broken SP120 Elite that I can test with but I'll try hooking it up. 

What does your Lighting setup in iCue looks like for the Lighting Node Pro (Pico) on that channel?

**Comment by cnn123666** [comment]
<img width="1026" alt="微信截图_20220202110000" src="https://user-images.githubusercontent.com/52467395/152086638-b30e1e76-d6f1-4059-97a2-0ee46a065b95.png">
<img width="1026" alt="微信截图_20220202110010" src="https://user-images.githubusercontent.com/52467395/152086641-ecc6701e-eff8-4af6-8432-37f72cbc0407.png">

**Comment by cnn123666** [comment]
![微信图片_20220202110259](https://user-images.githubusercontent.com/52467395/152086856-6549691e-0f1c-4d19-908e-5b165a94385a.jpg)

**Comment by cnn123666** [comment]
@Spegs21 I think it's the sketch

**Comment by Spegs21** [comment]
@cnn123666 Yes, I think it is too. You can add `CLP::printFps(5000);` after `FastLED.show();` to get an idea of how often it's refreshing. Make sure you call `Serial.begin(115200);` in `setup()`.

I tested this with the TinyUSB sketch on a Trinket M0 and the refresh rate was pretty low. I stepped through the code with a SWD debugger and it doesn't seem like it's receiving the LED_WRITE_TRIGGER command from iCue as often as needed to keep a smooth refresh rate. We probably need to get @Legion2  involved with this.

**Comment by Legion2** [comment]
Can you measure the time it takes to process an USB request, so the total time it takes to receive all bytes from the host and process them and send back all response bytes?

**Comment by Legion2** [comment]
I also use iCUE 4

**Comment by Legion2** [comment]
Can you print which commands are received

**Comment by Spegs21** [comment]
@Legion2 I did a quick ratio for my setup (LNP, 1 channel, 1 8-LED Series Fan) and I'm getting a 1:5 ratio of WRITE_LED_TRIGGER to any other WRITE_LED command. I'll add some debug lines to LEDController.cpp to print out the commands.

**Comment by Legion2** [comment]
1:5 should be fine

**Comment by Spegs21** [comment]
@Legion2 I implemented a debug macro system which I can open a PR for. Here is the pattern it is receiving:

```
Received command
>>>>	0x0	0x1	0x2	0x3	0x4	0x5	0x6	0x7	0x8	0x9	0xA	0xB	0xC	0xD	0xE	0xF
0x00	32	00	00	08	00	63	51	38	1D	02	00	00	0C	00	00	00
0x10	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
0x20	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
0x30	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
Sent response
>>>>	0x0	0x1	0x2	0x3	0x4	0x5	0x6	0x7	0x8	0x9	0xA	0xB	0xC	0xD	0xE	0xF
0x00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
Received command
>>>>	0x0	0x1	0x2	0x3	0x4	0x5	0x6	0x7	0x8	0x9	0xA	0xB	0xC	0xD	0xE	0xF
0x00	32	00	00	08	01	00	00	00	00	00	54	AF	FF	00	00	00
0x10	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
0x20	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
0x30	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
Sent response
>>>>	0x0	0x1	0x2	0x3	0x4	0x5	0x6	0x7	0x8	0x9	0xA	0xB	0xC	0xD	0xE	0xF
0x00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
Received command
>>>>	0x0	0x1	0x2	0x3	0x4	0x5	0x6	0x7	0x8	0x9	0xA	0xB	0xC	0xD	0xE	0xF
0x00	32	00	00	08	02	E3	D0	D7	EA	FD	AB	50	00	00	00	00
0x10	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
0x20	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
0x30	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
Sent response
>>>>	0x0	0x1	0x2	0x3	0x4	0x5	0x6	0x7	0x8	0x9	0xA	0xB	0xC	0xD	0xE	0xF
0x00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
Received command
>>>>	0x0	0x1	0x2	0x3	0x4	0x5	0x6	0x7	0x8	0x9	0xA	0xB	0xC	0xD	0xE	0xF
0x00	33	FF	00	00	00	00	00	00	00	00	00	00	00	00	00	00
0x10	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
0x20	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
0x30	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
Sent response
>>>>	0x0	0x1	0x2	0x3	0x4	0x5	0x6	0x7	0x8	0x9	0xA	0xB	0xC	0xD	0xE	0xF
0x00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
Received command
>>>>	0x0	0x1	0x2	0x3	0x4	0x5	0x6	0x7	0x8	0x9	0xA	0xB	0xC	0xD	0xE	0xF
0x00	38	00	02	00	00	00	00	00	00	00	00	00	00	00	00	00
0x10	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
0x20	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
0x30	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
Sent response
>>>>	0x0	0x1	0x2	0x3	0x4	0x5	0x6	0x7	0x8	0x9	0xA	0xB	0xC	0xD	0xE	0xF
0x00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00	00
```

**Comment by Legion2** [comment]
This looks completely normal

**Comment by Legion2** [comment]
the printFps function must be used in the `if (ledController.updateLEDs())` block

**Comment by Spegs21** [comment]
> the printFps function must be used in the `if (ledController.updateLEDs())` block

I know, I was just using to to time the loop with just USB interactions to check if USB communications was the bottleneck.

**Comment by Legion2** [comment]
your measurement of the command processing duration is 0ms, is this correct, can you use a better resolution or verify that your measurement method works?

**Comment by Spegs21** [comment]
@Legion2 There was a problem with my original timing implementation. I've corrected that and increased the resolution. THe worse I've seen is just over 5ms response time:
```
Received command 32 at 36070285us
Write LED color values
Sent response 00 at 36075376us (5091us response time)
Received command 32 at 36080166us
Write LED color values
Sent response 00 at 36085256us (5090us response time)
Received command 32 at 36094125us
Write LED color values
Sent response 00 at 36095137us (1012us response time)
Received command 33 at 36102129us
Write LED trigger
Sent response 00 at 36104580us (2451us response time)
Received command 38 at 36116532us
Write LED mode
Sent response 00 at 36116888us (356us response time)
```

**Comment by Legion2** [comment]
What is the fps value if you use it in the if block

**Comment by Spegs21** [comment]
It shows 24.8 fps.

**Comment by Legion2** [comment]
I think this is a normal refresh rate for icue, I think this is not the problem for the slow animations

**Comment by Legion2** [comment]
With the LS100 iCUE device it should be possible to get 135LEDs per channel or with the commander pro you can get more than 200 per channel if you select QL fans.

Does only the fps decrease or also the usb request duration go up?

**Comment by Spegs21** [comment]
@Legion2 With the setup I described (generic LEDs strip, 1.4m + 250mm on both channels) the longest response time was 5.2ms. They were higher in general, minimum of about 3ms.

**Comment by cnn123666** [comment]
Use 6 QL fans to see

**Comment by cnn123666** [comment]
@Spegs21 the frame rate varies with the number of beads

**Comment by cnn123666** [comment]
https://user-images.githubusercontent.com/52467395/153577654-686957cf-c94e-44d9-9199-2d25bfe11acb.mp4

**Comment by Spegs21** [comment]
> Use 6 QL fans to see

7.4 fps with this setup

**Comment by Legion2** [comment]
Only with Pi Pico or also with other boards?

**Comment by cnn123666** [comment]
I only have a Pico board. Why is that? Does USB data processing take too long?

**Comment by Spegs21** [comment]
@Legion2 I went back and tested this with the Trinket M0 and performance is identical. I've tried a few things to try to solve this but nothing I've done has made the slightest difference:
- Overclock the Pico to 250Mhz
- Disable interrupts in FastLED
- Increase FASTLED_INTERRUPT_RETRY_COUNT
- Increase the response size to 64 bytes

USB response times seem reasonable with no baseline to compare to. Wireshark shows the response coming through in less than 8ms while the Pico shows it's responding in less than 30us (I'm guessing it's just queueing the transfer until it's ready).

**Comment by Spegs21** [comment]
@Legion2 I just tried sharing the IRQ between TinyUSB and FastLED and increasing the TinyUSB interrupt from 1000us to 10000us and neither made any difference either.

I'll implement the histogram and see what we get.

**Comment by Legion2** [comment]
During your tests with different number of leds, did you only change the LEDs in icue, or did you increased and decreased them in the sketch and recompiled it? If only changed in icue FastLED always should take the same amount of time to rendered the leds, because it is independent of the number send by icue

**Comment by cnn123666** [comment]
Change only in ICUE

**Comment by cnn123666** [comment]
<img width="516" alt="微信截图_20220214191509" src="https://user-images.githubusercontent.com/52467395/153854130-2cbc8425-e960-4ec1-894c-706cd0b0239d.png">

https://user-images.githubusercontent.com/52467395/153854171-bd1292a3-c3fe-4a0b-83e8-4b8877583be4.mp4

**Comment by Legion2** [comment]
@Spegs21 can you also include the time it tooks from the end of the loop to the beginning of the next invocation, maybe there are some task running we don't know of

**Comment by Spegs21** [comment]
@Legion2 Here are the histograms for 10k loops. Inner loop is the sketch loop and outer loop is the core loop (between the end of the sketch loop and beginning of the next one):

![image](https://user-images.githubusercontent.com/23659000/153919715-c92ddf0e-381d-4c08-bdc0-9b88cc9ceb57.png)


![image](https://user-images.githubusercontent.com/23659000/153919746-49067be7-714e-4c4f-8ec6-04770569579e.png)

**Comment by Legion2** [comment]
The idle loop is too fast, it produces to much samples in the histogram can we filter them out or use a logarithmic scale?

**Comment by Spegs21** [comment]
@Legion2 @cnn123666 I can't believe I missed this. I had the HID polling interval set to **10ms**...

https://github.com/Legion2/CorsairLightingProtocol/blob/ba2f6e8cae0c34c66885f4f13adc89c8cde512d4/src/CorsairLightingProtocolTinyUSBHID.cpp#L28

Changing the 10 to 1 appears to fix the issue. I'll fix it in a PR.

**Comment by Spegs21** [comment]
See #270

**Comment by Legion2** [comment]
I release [0.15.0](https://github.com/Legion2/CorsairLightingProtocol/releases/tag/v0.15.0) which includes support for Pi Pico. It will be available in the Arduino IDE in about an hour.
