### ISSUE TITLE
Pro micro disconnects

### ISSUE THREAD

**Issue by skylersell** [Legion2/CorsairLightingProtocol#250]
**Describe the problem**
I have an issue with my pro micro freezing while in use. If I unplug it and in again it will work sometimes.

![image](https://user-images.githubusercontent.com/62623383/137598056-c99b14ff-90db-4cdd-b9f3-3472fc80c473.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Board: Clone pro micro 5v
 - Device: ls100
 - Version of IDE: Arduino IDE 1.8.16
 - Version of CLP: 0.14.2
 - Version of CLP Boards: 0.3.1
 - Sketch: ls100
**Code changes**
No code changes

If you need any other info I will try to provide it.

**Comment by skylersell** [comment]
When ever its disconnected it shows two red lights along with a green one dose this mean anything all are solid.

**Comment by Legion2** [comment]
which arduino clone do you have?

**Comment by Legion2** [comment]
how did you connect the arduino to your leds and how are the leds powered?

**Comment by skylersell** [comment]
I used my pc power supply and connected the ground and data wire to the ledsOn Oct 21, 2021 3:06 PM, Leon Kiefer ***@***.***> wrote:
how did you connect the arduino to your leds and how are the leds powered?

**Comment by Legion2** [comment]
How many leds do you have connected and configured in iCUE?
