### ISSUE TITLE
Support other MCU through 16U2

### ISSUE THREAD

**Issue by cnn123666** [Legion2/CorsairLightingProtocol#255]
I designed the 16U2 as a module
![QQ图片20211114112604](https://user-images.githubusercontent.com/52467395/141666272-a89c5628-90d1-4478-bd9c-5f864b21cdfd.png)
I'd like to upload HoodLoader2UnoMegaController to other muc

**Comment by Legion2** [comment]
The 16u2 doesn't have enough memory

**Comment by cnn123666** [comment]
I want to use ATmega16U2 to handle communication, AND I want to upload sketches to ATmega644, or some other MCU

**Comment by cnn123666** [comment]
![QQ截图20211114220207](https://user-images.githubusercontent.com/52467395/141684435-6ad2e5d7-e39e-40de-906c-92d4803a7371.png)

**Comment by Legion2** [comment]
Did you try to upload the controller sketch to the ATmega644 and have an error, or what is currently the problem?

**Comment by cnn123666** [comment]
I try to compile HoodLoader2UnofficialMegaController, but the compiler error
![微信截图_20211115065417](https://user-images.githubusercontent.com/52467395/141702100-2dde5dcf-bb31-4551-b487-ff860f6413d2.png)
![微信截图_20211115065728](https://user-images.githubusercontent.com/52467395/141702111-13e8c2a2-2bcf-4865-8b7f-855648b55043.png)
Maybe this ATmega644 doesn't support HID Bridge?

**Comment by Legion2** [comment]
The problem is that the file `HID.h` does not exist for your board. It must not contain an actual implementation, but must exist.

**Comment by cnn123666** [comment]
Thanks for your reply. I understand that if my chip doesn't have HID. H, I can't send data through 16U2, right?

**Comment by cnn123666** [comment]
Maybe I can try 8266, it seems to have HID. H

**Comment by Legion2** [comment]
You can try to add the HID.h file next to your sketch file

**Comment by Legion2** [comment]
Else I will need to update the library to exclude this file. But currently I have no time for this.

**Comment by cnn123666** [comment]
Thank you very much. I already know what I'm going to do, I'm going to end this problem until I get something new, okay
