### ISSUE TITLE
Arduino Uno with 8u2 not supported?

### ISSUE THREAD

**Issue by Shadowex3** [Legion2/CorsairLightingProtocol#262]
**Describe the problem**
My Arduino Uno has an 8u2 and not a 16u2, meaning its incompatible with the CLP HoodLoader2 16u2 board selected at step 7 [here](https://github.com/Legion2/CorsairLightingProtocol/wiki/How-to-use-on-Arduino-Uno-and-Arduino-Mega)

**Screenshots**
NA

**System (please complete the following information):**
 - OS: Win10
 - Board: Arduino Uno
 - Device: Lighting Node Pro
 - Version of IDE: NA
 - Version of CLP:  0.14.2
 - Version of CLP Boards:  0.3.1
 - Sketch: HoodLoader2CLPBridge

**Code changes**
NA

**Comment by Legion2** [comment]
I think the 8u2 has not enough memory, can you try to select the non "CLP" version of the board and compile the sketch and then report the memory usage.
