### ISSUE TITLE
Cannot change emulated device type

### ISSUE THREAD

**Issue by netdudeuk** [Legion2/CorsairLightingProtocol#263]
Hi

I created a simulated Lighting Node Pro with eight LEDs and that works ok thanks.

I decide to download the LT100 sketch (changing the number of LEDs to eight) but iCUE says that I still have a LNP after the _Done uploading_ message.

I also get the same result if I try the LS100 sketch.

I only have one CorsairLightingProtocol device connected.

Any ideas please ?

Thanks

**Comment by Legion2** [comment]
You have the select the correct board as shown here https://github.com/Legion2/CorsairLightingProtocol/blob/dev/extra/images/select-board.png

**Comment by netdudeuk** [comment]
Thanks for the prompt reply.

I checked the setting and discovered that there's a Device setting that also has to be changed.  So, my mistake.  I do now see the device in iCUE but the LED Detection Run button doesn't detect the 'tower'.  I must be missing something else.

**Comment by Legion2** [comment]
What 'tower' do you have? The detection feature is implemented in such a way that it uses the number of configured leds in the sketch
