### ISSUE TITLE
Multiple rgb fans

### ISSUE THREAD

**Issue by MerlijnMoonen** [Legion2/CorsairLightingProtocol#264]
I have a pro micro 5v and, I wondered if I can assign 1 fan to 1 datapin.

I have 4 fans with 10 leds in my pc and I want them all to have a different color. 

With the standard code for the node pro  I can only have 2 with different colors.

What do I have to add so I can assign each fan to a datapin?

Merlijn

**Comment by Legion2** [comment]
Have a look at the [MultipleFans](https://github.com/Legion2/CorsairLightingProtocol/blob/dev/examples/MultipleFans/MultipleFans.ino) example.

**Comment by MerlijnMoonen** [comment]
Thanks it works
