### ISSUE TITLE
can not verify for raspberry pi pico board 

### ISSUE THREAD

**Issue by fredycz2005** [Legion2/CorsairLightingProtocol#268]
![image](https://user-images.githubusercontent.com/91020239/152822578-888409fd-60c9-497f-a099-f2bb9c81b4a0.png)
I tried to use ls100 for raspberry pi pico but i can not verify the sketch

**Comment by cnn123666** [comment]
https://github.com/Legion2/CorsairLightingProtocol#create-a-lighting-node-pro-for-a-raspberry-pi-pico-with-tinyusb

**Comment by fredycz2005** [comment]
i tried it but i do not see tinyUSB anywhere in the example list and neither in corsair protocol example list

**Comment by Legion2** [comment]
the version with tinyUSB is not released jet #267

**Comment by Legion2** [comment]
I release it in [0.15.0](https://github.com/Legion2/CorsairLightingProtocol/releases/tag/v0.15.0), it will take an hour to be available in the Arduino IDE.
