### ISSUE TITLE
Difficulty of adding support for WLED lights?  (re: FastLED alternative for RGBW lights)

### ISSUE THREAD

**Issue by sofakng** [Legion2/CorsairLightingProtocol#269]
What is the difficulty of adding support for communication to RGBW lights using WLED?  (ie. this project would create a bridge device to go between CLP and WLED)

The advantage is that it would support many additional light modules, but more specifically RGBW lights.

Alternatively, what is the difficulty to switch from FastLED to a different LED library that does support RGBW lights?

**Comment by Legion2** [comment]
You can convert the led output of this library to any library you want. The led data is in a very simple format which you can convert to any other formats.
