### ISSUE TITLE
How to convert LC100 to normal strip format

### ISSUE THREAD

**Issue by cnn123666** [Legion2/CorsairLightingProtocol#271]
<img width="1026" alt="20220217223728" src="https://user-images.githubusercontent.com/52467395/154504039-fe0fdf1c-afcf-40b5-8547-75a7afbe7d11.png">

**Comment by cnn123666** [comment]
https://user-images.githubusercontent.com/52467395/154504312-42360867-565c-48e2-bd9d-bea86a6d93c8.mp4

This is his order. 4,5,6,7,8,9,1,2,3
<img width="650" alt="20220217224021" src="https://user-images.githubusercontent.com/52467395/154504559-9e6e4138-729a-452b-95e1-45f188338639.png">
I notice this function, but I don't know how to change it

**Comment by Spegs21** [comment]
It'll be a very similar function. You'll just have to std::rotate the array in groups of 9 enough times to put it in order. I can probably write it if I get a chance.

**Comment by cnn123666** [comment]
LIGHTING NODE PRO now supports 18 LC100 (162) and 6 QL fans (204). A maximum of 366 beads

**Comment by Spegs21** [comment]
@cnn123666 Are you sure? If I select 6 QL fans on one channel it disables the other channel with the Lighting Node Pro sketch.

**Comment by cnn123666** [comment]
You can add 18 LC100s in channel 1, and you can add other devices in channel 2.

**Comment by cnn123666** [comment]
Can the

**Comment by cnn123666** [comment]
![20220219115231](https://user-images.githubusercontent.com/52467395/154785088-c08357a5-6b5d-467b-86fa-8c71f38d457d.png)

**Comment by Spegs21** [comment]
Interesting... Is this with a newer update to iCue? I'll have to look into it.

**Comment by cnn123666** [comment]
@Spegs21 Update to the latest ICUE

**Comment by Spegs21** [comment]
@cnn123666 I'm convinced this is a bug with iCue channel set up and LC100. In your last screenshot, if you were to click the dropdown for channel 1, the only option it would give you is "No Device Connected". The LED limiting channel interactions are not working properly like they do for other devices. If you changed your channel 2 to 5 QL fans and changed your device on channel 1 to something else then back to LC100 it will only let you add 2 companion triangles.

That being said, if you change the tudHid polling interval from 1ms to 0ms (@Legion2 this works) in the Adafruit_USBD_HID constructor, the Pico can maintain the full 25 FPS addressing all 366 LEDs in the bugged set up.

**Comment by cnn123666** [comment]
I don't think it's a BUG 。Now the ICUE UI displays normally
<img width="1026" alt="20220301211112" src="https://user-images.githubusercontent.com/52467395/156175593-14af16d7-3d77-4080-90da-1e958c226748.png">

**Comment by Spegs21** [comment]
This has less total LEDs (297) than the setup with 6 QL fans and 18 LC100s so it's probably allowed.

**Comment by Spegs21** [comment]
@cnn123666 Can you test the function from my repo?
`CLP::TransformLC100ToStrip`

**Comment by cnn123666** [comment]
Can I only use it on the 32U4？
<img width="837" alt="304200040" src="https://user-images.githubusercontent.com/52467395/156759989-c0ccc2bf-1ab6-4fc2-90af-353b50f9cd15.png">

**Comment by cnn123666** [comment]
@Spegs21 Hello! I tested it on the 32U4 and it worked. Also fixed to light strip format. But it doesn't compile on pico

**Comment by Spegs21** [comment]
@cnn123666 It compiled OK on pico for me. It looks like your build log is showing it's trying to include a broken wifi library. It shouldn't be doing that. Do you have an extra include at the top?

**Comment by cnn123666** [comment]
@Spegs21 I'm sorry for my problem. After the Arduino was restarted, the compilation was successful. Thank you very much for your help.
