### ISSUE TITLE
raspberry pi pico as ls100

### ISSUE THREAD

**Issue by fredycz2005** [Legion2/CorsairLightingProtocol#272]
hello.
How can i use the raspberry pi pico as ls100, because the scatch for tiny usb is only for lightning node pro ??

**Comment by Legion2** [comment]
You have to modify the sketch to emulate the LS100 corsair product type, replace `CORSAIR_LIGHTING_NODE_PRO` with `CORSAIR_SMART_LIGHTING_CONTROLLER`. @Spegs21 correct me if I'm wrong.

**Comment by fredycz2005** [comment]
thank you for your help
