### ISSUE TITLE
arbg for 4 pin motherboards

### ISSUE THREAD

**Issue by DavrosUnderwood** [Legion2/CorsairLightingProtocol#275]
hi
my motherboard is Maximus ix code so i have 4 pin header for rgb like this
![image](https://user-images.githubusercontent.com/74089624/155935666-6e8fe0b0-c1ac-4ad9-b8ef-cb622a178eff.png)
is there anyway to convert that to argb ? or use something else like usb for connecting to pc?

**System (please complete the following information):**
 - OS: Windows 10
 - Motherboard: Maximus ix code
 - Board: Arduino Leonardo

**Comment by Legion2** [comment]
If you want to use Arduino, then you can ignore your Mainboard connectors and just use an Arduino with CLP. It supports both argb and non addressable LEDs.
