### ISSUE TITLE
use of the RPM and the 4 sensors in commander pro?

### ISSUE THREAD

**Issue by serlancelot** [Legion2/CorsairLightingProtocol#278]
Hello, I have a question... Is there an update planned to be able to use the RPM and the 4 temperature sensors in the commander pro?  I have done it with arduino, with esp or raspberry can all the options be used or is it the same?  Thank you!

**Comment by Legion2** [comment]
Do you mean the RPM tacho signal of PWM fans? This is currently not supported by any board and I have no plan to add support. But I'm open to contributions.
