### ISSUE TITLE
Is it possible to connect any argb device with the arduino or do these work different?

### ISSUE THREAD

**Issue by AquaCobell** [Legion2/CorsairLightingProtocol#283]
I was thinking of linking all my argb devices including some fans and the lian li strimmer plus cause msi mystic light is really bad, is this theoretically possible or do these work different than normal ws2812 stripes?

**Comment by Legion2** [comment]
yes theoretically its possible to link any device, as long as you know the type of leds it uses and how its wired.

**Comment by AquaCobell** [comment]
thanks that sounds very good, what do you exactly mean by types of leds? I thought every argb devices uses ws2812 or something working the same, or could they have different ones when using an argb header?

**Comment by Legion2** [comment]
Yes they use some kind of ledchipset, which can be configured with the FastLED library which is included in every example sketch.

**Comment by JoseArtunedo** [comment]
In principle this would be to emulate non-physical devices and obtain the benefits and functions of iCue.

If you have the original devices, there are other projects; where it identifies all the devices and synchronizes them all, without having to use MystiLight, iCue, etc.

In short, with a single software you can synchronize all your devices from different brands, even using different types of LEDs. This software is very well known and I don't want to spam other projects here.

In fact, in the initial post it refers to compatible third-party software, it appears there.
