### ISSUE TITLE
Backlight with less LED, 8 fisical Leds to 15 channels

### ISSUE THREAD

**Issue by Mbumbleb** [Legion2/CorsairLightingProtocol#286]
**Describe the problem**
guys, can i make a ambient lighting LS200 with less leds?! my config is 9 ld on side and 25 on top and botton... but icue use 15/27
i try use SegmentScaling , but not show on icue if led<channels

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 11
 - Board: Arduino Leonardo
 - Device: Smart Lighting Controller
 - Version of IDE:  Arduino IDE 1.8.19
 - Version of CLP: [e.g. 0.15.0]
 - Version of CLP Boards: [e.g. 0.2.0]
 - Sketch: [e.g. AmbientBacklight

**Code changes**
ledController.onUpdateHook(0, []() {
    CLP::SegmentScaling segments[4] = {{15, 9}, {27, 25}, {15, 9}, {27, 25}};
    CLP::scaleSegments(&ledController, 0, segments, 4);
    CLP::scale(&ledController, 1, 84);
		// increase the brightness of channel 1 when using iCUE, because iCUE only set brightness to max 50%
		CLP::fixIcueBrightness(&ledController, 0);
    CLP::fixIcueBrightness(&ledController, 1);

**Comment by Legion2** [comment]
iCUE will always show  15/27, but the arduino will map the leds for you. If you want to use less leds than icue, you still have to configure the `CRGB ledsChannel[84];` to have at least the number of leds shown in icue.
