### ISSUE TITLE
how to use 400 leds with arduino? it's possible?

### ISSUE THREAD

**Issue by fanchij** [Legion2/CorsairLightingProtocol#287]
Hello, I am trying to use more than 400 LEDs in a single strip and a single channel, but I cannot use more than 280 LEDs. I am using an arduino UNO

#include <CorsairLightingProtocol.h>
#include <FastLED.h>

// Hint: The Arduino Uno does not have as much memory as the Arduino Mega, it may be that problems occur when a higher
// value is set here.
#define CHANNEL_LED_COUNT 60

#define DATA_PIN_CHANNEL_1 2

CorsairLightingFirmwareStorageEEPROM firmwareStorage;
CorsairLightingFirmware firmware(CORSAIR_LIGHTING_NODE_PRO, &firmwareStorage);
FastLEDControllerStorageEEPROM storage;
FastLEDController ledController(&storage);
CorsairLightingProtocolController cLP(&ledController, &firmware);
CorsairLightingProtocolSerial cLPS(&cLP);

CRGB ledsChannel1[350];

void setup() {
  /*
  YOU MUST NOT USE Serial!
  Serial is used by CorsairLightingProtocolSerial!
  */
  cLPS.setup();
  FastLED.addLeds<WS2812B, DATA_PIN_CHANNEL_1, GRB>(ledsChannel1, 350);
    ledController.addLEDs(0, ledsChannel1, 60);
  //  ledController.onUpdateHook(0, []() {
  //    CLP::repeat(&ledController, 0, 2);
  //  });
  ledController.onUpdateHook(0, []() {
        CLP::scale(&ledController, 0, 350);
  });
}

void loop() {
  cLPS.update();

  if (ledController.updateLEDs()) {
    FastLED.show();
  }
}

**Comment by Legion2** [comment]
What is the error? Or what exactly is the problem
