### ISSUE TITLE
ICUE does not identify.

### ISSUE THREAD

**Issue by willianazambuja** [Legion2/CorsairLightingProtocol#29]
Was using version 0.3.0, was working everything right identified in the application. I ended up getting a new arduino, I went to the version 0.4.0 in the new arduino and without wanting to finish what was working. now it does not identify anymore in the icue, if a mute the PID = 0c0b for PID = 0c0c it appears only that it is the same as the image. and in the new arduino the same [thing.](http://prntscr.com/odr5vg)

**Comment by Legion2** [comment]
Which arduino, iCUE version, OS?
Do you have to arduinos connected at the same time?
Which sketch did you used?
Why you not using the Issue Tech-support template?

PS: you can include images natively in GitHub no need for file hoster

**Comment by willianazambuja** [comment]
ICUE version: 3.17.94. Windows 10.
only one connected arduino.
![Screenshot_4](https://user-images.githubusercontent.com/4706613/61076132-e8d17e00-a3f1-11e9-9efa-8c8d7c3a8939.png)

**Comment by Legion2** [comment]
`cLNP.begin();` is missing in the `setup` method.

**Comment by Legion2** [comment]
https://github.com/Legion2/CorsairLightingProtocol/blob/v0.4.0/examples/LightingNodePRO/LightingNodePRO.ino#L31 this is the example sketch for v0.4.0, you are using the example sketch of `dev` (v0.5.0).

**Comment by Legion2** [comment]
now v0.5.0 is release so, this sketch should work with the library from the library manager.
