### ISSUE TITLE
FAN LED HUB

### ISSUE THREAD

**Issue by theorgBigBoss** [Legion2/CorsairLightingProtocol#290]
**Describe the problem**
Hi
i want to controll custom argb fan and i realize i need LED HUB to do this like corsair
i need another arduino?
how can i make one?

**System (please complete the following information):**
 - OS: Windows 10
 - Board: Arduino Leonardo
 - Device: Lighting Node PRO
 - Version of IDE: IDE 1.8.13
 - Version of CLP: 0.15.0
 - Version of CLP Boards: 0.2.0
 - Sketch: LNP

**Comment by Legion2** [comment]
Have a look at https://github.com/Legion2/CorsairLightingProtocol/blob/dev/examples/MultipleFans/MultipleFans.ino, this example controls multiple fans on different pins, just like a fan hub.
