### ISSUE TITLE
Hardwaremode render functions are not all working

### ISSUE THREAD

**Issue by HasseM** [Legion2/CorsairLightingProtocol#297]
**Describe the bug**
Most hardwaremode render functions are not working.

**To Reproduce**
Set hardwaremode (e.g. lock your screen in windows) and see that staticcolor, color pulse, color shift are not working. Rainbow wave, Marquee do work. (this is not a complete list)

I have been testing and debugging the code with the renderStatic function.
if I change renderStatic (FastLEDController.cpp Ln 202) from:
```
bool FastLEDController::renderStatic(ChannelData& channelData, LEDGroup& group, int groupLedCount) {
	fill_solid(&channelData.leds[group.ledIndex], groupLedCount, group.color1);
	return true;
}
```
to:
```
bool FastLEDController::renderStatic(ChannelData& channelData, LEDGroup& group, int groupLedCount) {
	int duration = applySpeed(100, group.speed);
	int count = animation_step_count(duration, 1);	
	if (count > 0) {
		fill_solid(&channelData.leds[group.ledIndex], groupLedCount, group.color1);
		return true;
	}
	return false;	
}
```
Then it works. For some reasons, the render function needs to return false sometimes. It's likely also the case for the other render functions.

Edit: I think it is a timing issue. I experience the Loop() function to be really really slow in the non-working situation. The render function is returning true all the time. This causes led updates each loop (ledController.updateLEDs() is always true). The change I made to the render function makes it return false most of the time. Then it works and loop() remains running normally. So if the render function wants to render each loop, the system seems to get overloaded and not working.

**Comment by Legion2** [comment]
Which arduino device are you using? Can you create a PR to fix the issue?

**Comment by HasseM** [comment]
> Which arduino device are you using? Can you create a PR to fix the issue?

RaspberryPi Pico

Can you tell me how to create a 'PR to fix the issue' ? I would be happy to help here!

**Comment by Legion2** [comment]
You need to fork this repository, do a git clone on the forked repository, fix the code, create a commit and the push the commit to your fork, from there you can create a Pull Request, which we can then discuss here on github.

**Comment by HasseM** [comment]
Yes, can do but I am not an expert on this code (yet). So if you feel that my proposed change is good, I will submit it. However I am just not sure if there is'nt a better solution then forcing a static situation to perform a fake animation. I just dont have the overview yet. I am in this code just a couple of days....
