### ISSUE TITLE
Unable to flash Uno Mega controller

### ISSUE THREAD

**Issue by adam120800** [Legion2/CorsairLightingProtocol#30]
**Describe the bug**
HoodLoader2UnoMegaController project wont compile. I am not much programming savvy and i use Arduino IDE always so i am a little lost when it comes properly reporting. I will attach as many screenshots as possible :D. I have included all libraries.

![Compiling Screen1](https://user-images.githubusercontent.com/52804185/61092185-9a4dcf00-a445-11e9-8699-c84b429a329e.PNG)
![Debug window1](https://user-images.githubusercontent.com/52804185/61092186-9a4dcf00-a445-11e9-9060-31d31b533a5d.PNG)
![Debug window2](https://user-images.githubusercontent.com/52804185/61092188-9ae66580-a445-11e9-978f-4c63c7661ddf.PNG)
![Error Window 1](https://user-images.githubusercontent.com/52804185/61092189-9ae66580-a445-11e9-94f9-c1dd8a5c91d5.PNG)

**System (please complete the following information):**
 - OS: Win 10
 - Board: Legit Arduino Uno with HoodLoader2 properly installed on 16u2
 - IDE: Visual Studio 2019
 - Version: Latest commit, downloaded as zip
 - Sketch: HoodLoader2UnoMegaController.ino

**Code changes**
None

**Comment by Legion2** [comment]
First screenshot looks like you have installed an older version of the library too. Use the library Manager to remove it and install the downloaded zip as library

**Comment by Legion2** [comment]
Left of the green play button change "Debug" to "Release" like [this](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-set-debug-and-release-configurations.md#change-the-build-configuration).

**Comment by Legion2** [comment]
I will release the version with Arduino Mega support soon, then you only have to update the library in the library manager.

**Comment by adam120800** [comment]
Awesome, thanks. I ,managed to manually update the library. Uploaded uno mega controller and clpbridge successfully to both main chip and 16u2. My arduino is recognized as lightining node pro, TX and RX are blinking but i have no output to my led's whatsoever

**Comment by adam120800** [comment]
Also i have no errors while compiling or anything similiar

**Comment by Legion2** [comment]
Debug the HoodLoader2CLPBridge sketch, add -DDEBUG in the board.txt of that sketch folder, upload HoodLoader2CLPBridge again and open serial monitor with rate 1000000

**Comment by adam120800** [comment]
Okay, i will do that tonight i am going to work currently
