### ISSUE TITLE
Would like help with Corsair iCUE

### ISSUE THREAD

**Issue by solidsemtex** [Legion2/CorsairLightingProtocol#302]
As i have seen, you guys have experience dealing with iCue. I would like to double the Led intensity when using "video Lightning" function on my LS100 Lightning Strips. Can you guys help me do it with just config files? Logitech and other brands have this function to increase intensity of the colors displayed on the screen to the LEDs, sadly Corsair doesn't.

I saw you guys have a fix but it involves boards and third party programs, i just want to edit a config file or something. Do you think it is possible? I read the RGBs are at 50%, just setting it up to 100% will do the trick, i believe.

If you can help me identify where to set it up without coding knowledge im willing to donate $20

Thanks and kind regards,

**System (please complete the following information):**
 - OS: Windows 11
 - Board: ?
 - Device: LS100 Starter Kit
 - Version of IDE: ??
 - Version of CLP: ??
 - Version of CLP Boards: ??
 - Sketch: [e.g. RepeatAndScale]

**Comment by Legion2** [comment]
The fix only works in combination with an Arduino custom LED controller and it only increases the brightness of the LEDs connected to the Arduino. I don't know of a solution to increase brightness in iCUE itself beyond what is shown as 100%.
