### ISSUE TITLE
Temperature does show 0.00°C when connecting a sensor

### ISSUE THREAD

**Issue by ma-mod** [Legion2/CorsairLightingProtocol#303]
Hello Legion2, 

At first, thanks for the awesome project.
I have installed a custom water cooling into my pc and want to grab the temperature from it. unfortunately the temperature drops to 0.00 the moment I connect the gpio pin and ground to the sensor.
this happens with a bykski temperature fitting but also with the original corsair temperature sensors.
any idea? 

Board is a Arduino Pro Micro.

Thank you in advance!

**Comment by Legion2** [comment]
To work with temperature sensors you must create a voltage divider circuit which requires an additional 10k resistor, see https://github.com/Legion2/CorsairLightingProtocol/blob/dev/examples/CommanderPRO/ThermistorTemperatureController.h#L25 for the schematic.
