### ISSUE TITLE
Read out RGB Values and LED Number for other use

### ISSUE THREAD

**Issue by JacTech** [Legion2/CorsairLightingProtocol#305]
Hi i currently have a diy nanoleaf project. Each nanoleaf has its own microchip wich communicates with the base arduino via I2c. 
I basically i would like to connect the base arduino with icue, read the RGB Value and number of the Pixel, icue sends it and send it to a nanoleaf pannel. 
So would it be possible to store the values ​​in an array (that i could read out in my code)  instead of sending them to a ws2812b strip?
if yes how?

**Comment by Legion2** [comment]
Yes the `ledsChannelx` variables store the array of RGB values, which are updated in the `loop`, instead of sending these values to ws2812b strip, you can read its values and send it to any destination you want.
