### ISSUE TITLE
Multi Usb Descriptor (More channels)

### ISSUE THREAD

**Issue by elmariolo** [Legion2/CorsairLightingProtocol#312]
I come with an idea. I know that both Arduino and R-pi-pico support sending a USB descriptor with multiple instances of a device.
I am in need of a version that can support multiple instances of Lighting Node Pro to use more than two outputs.
The idea is to be able to control each fan/LED strip independently, creating fabulous effects.
In iCue it would look like multiple devices connected, as opposed to just one per arduino/pico.
This is achieved by modifying the USB configurations by sending a descriptor with a collection of more than one device (changing the 
 0x85 report ID value) and handling the messages for each one independently.
 Unfortunately, C/C++ is a language that I don't have enough knowledge to do it myself, but I understand that the class should be adjusted so that it accepts several instances and the constructor have to receive the serial and ID for one each of them.
 I hope this can be achieved, so all the outputs of an arduino/pico could be used.
 RGDS,
 Mario.

**Comment by Legion2** [comment]
Can you try to make a PR, where you make the changes you explained. It does not have to be correct C++ but I is much easier for us to understand what needs to be changed.
