### ISSUE TITLE
HID Error

### ISSUE THREAD

**Issue by Baumart** [Legion2/CorsairLightingProtocol#318]
I have build a Macro Keypad and want to intigrait RGB effectivs with my RGB software, but the problem ist that HID thing:
Render():140 Error: device.write(): HID handle is invalid, confirm that the protocol type selected is HID.
![image](https://user-images.githubusercontent.com/89712869/210425831-1001b934-6bf3-4d68-b059-8b47975b1063.png)

-Arduino Pro Micro
-SingalRGB

**Comment by Legion2** [comment]
Where does this error message come from? Please use the signal RGB support if the sketch is from Signal RGB.
