### ISSUE TITLE
Error While Compiling TinyUSB Sketch

### ISSUE THREAD

**Issue by d3m0-sm** [Legion2/CorsairLightingProtocol#323]
**Describe the problem**
A clear and concise description of your problem.

**Screenshots**

**System (please complete the following information):**
 - OS: Windows 10
 - Board: Raspberty Pi Pico
 - Device: TinyUSB
 - Version of IDE: Arduino IDE 1.8.19
 - Version of CLP: 0.15.0
 - Sketch: [TinyUSB]

**Code changes**
ledsChannel11 and 22 from 96 to 22.

If i try to compile the example sketch, i get the Error: "CorsairLightningProtocolT inyUSBHID' does not name a type; did you mean CorsairLightningProtocolController?"

**Comment by Legion2** [comment]
Either you have not selected the "Adafruit TinyUSB" USB Stack or you have a typo in your your code.
