### ISSUE TITLE
Is this a Bug: My Arctic LED ARGB Fans are not running, Protocol issues?

### ISSUE THREAD

**Issue by Hitower78** [Legion2/CorsairLightingProtocol#324]
**Describe the bug**

**To Reproduce**
1. Change to '...'
2. Upload '....'
3. See error

**Expected behavior**

> i notice, that ARTIC LED Fans are not running with this COntroller. Mine is base on a Arduino Pro Micro
> Many LED Stripes and Rings are Running. (eg. Intertech argb fans)
> But not that from Arctic (PWM aRGB and Freezer aRGB). Did there use a special Protocol?
> a tiny argb controller (sata DC plugin, 3 pin ardgb out) is good on that arctic LED Fans...
> so there is a kind of difference between the Icue and the tiny controller protocol

**Screenshots**
Same Connection as to some LED stripes (30cm, 3 Pin Connection V Di, G)

**System (please complete the following information):**
 - OS: [e.g. Windows 10]
 WIn 10, Icue 4.33,  Firmware 99,40
 
- Board: [e.g. Arduino Leonardo]
Arduino Pro Micro 

 - Device: [e.g. Lighting Node PRO]
 Lightning Node Pro, Firmware 99,40

 - Version of IDE: [e.g. Arduino IDE 1.8.13]
 Arduino IDE 1,8.13

 - Version of CLP: [e.g. 0.15.0]
 0.3.1
 - Version of CLP Boards: [e.g. 0.2.0]
 
- Sketch: [e.g. RepeatAndScale]
 -
Could be a software Issue in the Libary?

**Code changes**
Did you changed the code of the library or the sketch?
No!

**Comment by Legion2** [comment]
To debug this problem we need to know what kind of LEDs are built into the Artic LED fans. Depending on the kind, some changes in the code are required to make them work.
