### ISSUE TITLE
Corsair Lightning Protocol - LS100 Repeat

### ISSUE THREAD

**Issue by Agademo** [Legion2/CorsairLightingProtocol#325]
As I have shown in the attached picture, I created an LS100 controller with Arduino Leonardo. With this controller, 135 pixel LEDs are currently on. You said before with this code that a maximum of 400 pixel leds can be lit. In the code prepared for the LS100
CRGB ledsChannel1[135];
CRGB ledsChannel2[54];
values ​​are available. How do I set the code so that I can light a maximum of 400 pixel leds?

Thank you for your help.

 - ![Adsız](https://user-images.githubusercontent.com/118980801/218700445-cf6d1efc-d33a-44f5-bcb8-64d4c44b3aab.png)

**Comment by Legion2** [comment]
Try this:

```c++
#include <CorsairLightingProtocol.h>
#include <FastLED.h>

// Hint: The channels of the LS100 are swapped in iCUE, so the first channel in iCUE is here channel 2
#define DATA_PIN_CHANNEL_1 2

#define BUTTON_PIN 4

// Hint: The ATmega32U4 does not have enough memory for 135 leds on both channels
CRGB ledsChannel1[400];

CorsairLightingFirmwareStorageEEPROM firmwareStorage;
CorsairLightingFirmware firmware(CORSAIR_SMART_LIGHTING_CONTROLLER, &firmwareStorage);
FastLEDControllerStorageEEPROM storage;
FastLEDController ledController(&storage);
CorsairLightingProtocolController cLP(&ledController, &firmware);
CorsairLightingProtocolHID cHID(&cLP);

void setup() {
	FastLED.addLeds<WS2812B, DATA_PIN_CHANNEL_1, GRB>(ledsChannel1, 400);
	ledController.addLEDs(0, ledsChannel1, 135);
        ledController.onUpdateHook(0, []() {
		CLP::scale(&ledController, 0, 400);
	});
}

void loop() {
	cHID.update();

	if (ledController.updateLEDs()) {
		FastLED.show();
	}
}
```

**Comment by Agademo** [comment]
> Bunu dene:
> 
> ```c++
> #include <CorsairLightingProtocol.h>
> #include <FastLED.h>
> 
> // Hint: The channels of the LS100 are swapped in iCUE, so the first channel in iCUE is here channel 2
> #define DATA_PIN_CHANNEL_1 2
> 
> #define BUTTON_PIN 4
> 
> // Hint: The ATmega32U4 does not have enough memory for 135 leds on both channels
> CRGB ledsChannel1[400];
> 
> CorsairLightingFirmwareStorageEEPROM firmwareStorage;
> CorsairLightingFirmware firmware(CORSAIR_SMART_LIGHTING_CONTROLLER, &firmwareStorage);
> FastLEDControllerStorageEEPROM storage;
> FastLEDController ledController(&storage);
> CorsairLightingProtocolController cLP(&ledController, &firmware);
> CorsairLightingProtocolHID cHID(&cLP);
> 
> void setup() {
> 	FastLED.addLeds<WS2812B, DATA_PIN_CHANNEL_1, GRB>(ledsChannel1, 400);
> 	ledController.addLEDs(0, ledsChannel1, 135);
>         ledController.onUpdateHook(0, []() {
> 		CLP::scale(&ledController, 0, 400);
> 	});
> }
> 
> void loop() {
> 	cHID.update();
> 
> 	if (ledController.updateLEDs()) {
> 		FastLED.show();
> 	}
> }
> ```

This is it! Thank you very much for your help my friend
