### ISSUE TITLE
commander pro problem

### ISSUE THREAD

**Issue by Black-Sparro** [Legion2/CorsairLightingProtocol#328]
good afternoon dear legion2.
thanks for you're hard work on this project. i test it and love it. it works great. however i find myself a problem that i can not debug. every sketch i use and upload, ICue software registers it as lightning node pro. i want to try commander pro but is no use. maybe i have to change device id or PID somewhere but i couldn't find any guide in git-hub or comment on code to solve it. my hardware is Arduino pro micro. needless to say with commander pro sketch, still i can use 2 ARGB channels.

**Comment by Legion2** [comment]
Hi, thanks, in the Tools menu you need to select the correct "Device" type you like to create:

![image](https://user-images.githubusercontent.com/12752323/220618034-aa58b38d-e997-4d20-9bca-8918e2f50972.png)

**Comment by Black-Sparro** [comment]
thanks a lot man.

**Comment by Black-Sparro** [comment]
works like a charm
