### ISSUE TITLE
Connect RGBW led

### ISSUE THREAD

**Issue by gavrilov** [Legion2/CorsairLightingProtocol#329]
Hello! 

I'm trying to figure out how to connect a single 5v RGBW led to arduino controller. 

I have a single led with this type of connector:

[PXL_20230223_191631868 MP](https://user-images.githubusercontent.com/11378530/221009507-e10e471b-bb72-46f4-aaca-182a1e527669.jpg)

I believe it will be something like 
/examples/NonAddressable/
but not sure what to do with white channel

Could you please help me?

**Comment by Legion2** [comment]
I don't know if the white channel is needed. But you can also calculate a white value from the RGB channels by using the minimum of them and then substract the white value from all the RGB channels.
