### ISSUE TITLE
How does Commander Pro get fan rpm input? 

### ISSUE THREAD

**Issue by forseenink3238** [Legion2/CorsairLightingProtocol#334]
I was checking the sketch for the commander Pro and it seems that it only has pwm fan control but not a fan tachometer input. If there is no tachometer input, how will iCUE know what speed the fan is running at?

 - OS: Windows 10
 - Board: Arduino pro micro
 - Device: Commander PRO
 - Sketch: Commander Pro 

No changes made to the sketch.

**Comment by Legion2** [comment]
The fan speed is not measured, instead we either set the fan speed to an expected value directly or calculate a value from the power by using linear interpolation from the min/max fan speed given in the constructor. We assume that the speed <> power correlation is linear and can then calculate the speed or assume it is a specific value given the power we supply to the fan. 
Of cause the assumption is never true in the real world, but this is the best we can do without measuring the fan speed.
If you like you can implement the measuring of the tacho signal and create a PR, but it is difficult the measure the tacho signal with all the other interrupts, USB data sending and receiving, and updating of the leds happening at the same time.

**Comment by forseenink3238** [comment]
> If you like you can implement the measuring of the tacho signal and create a PR, but it is difficult the measure the tacho signal with all the other interrupts, USB data sending and receiving, and updating of the leds happening at the same time.

I'm not very good with programming but I could try, what if I remove the led lighting controller from the code to reduce the load on the microcontroller and ram?

**Comment by forseenink3238** [comment]
Also which temp sensor is compatible with this code?

**Comment by Legion2** [comment]
You can replace the led lighting controller with a no-op implementation, but not completely remove it.

> Also which temp sensor is compatible with this code?

standard 10K temp resistor, there is a schematic in the temp sensor code how to wire it
