### ISSUE TITLE
How to connect two or three LT100 or LS100

### ISSUE THREAD

**Issue by cjgun** [Legion2/CorsairLightingProtocol#339]
I made three different ones. LT100, LS100 and NODE PRO all three are visible in iCUE, but if I make another LT or LS, only one is visible, although both are present in the system, this is visible on com ports.

Perhaps somewhere you can fix the ID or PID in the uploaded firmware?

I have 3 monitors and I wanted to make my own ambilight for each.

Thanks for the reply in advance.

**Comment by Legion2** [comment]
Have a look at https://github.com/Legion2/CorsairLightingProtocol#use-of-multiple-devices, you have to set unique IDs for the devices.
