### ISSUE TITLE
More than 2 channels 

### ISSUE THREAD

**Issue by 400R** [Legion2/CorsairLightingProtocol#343]
Is it possible to utilise more than 2 channels on one device because using 2 devices causes them to change order and the channels that are set need  to be reset
 If it's possible how do I add more channels?

**Comment by Legion2** [comment]
iCue only supports two channels, you need to use multiple devices with different device IDs.

**Comment by 400R** [comment]
OIk cheers. 
So i can just change that in the code before compiling?

**Comment by Legion2** [comment]
Here is the [documentation on how to use multiple devices](https://github.com/Legion2/CorsairLightingProtocol#use-of-multiple-devices).
