### ISSUE TITLE
is there any way to add 10 fans in multiple sketch code? 6 individual fans on channel 1 and 4 on channel 2. i am using arduino pro micro.

### ISSUE THREAD

**Issue by hasbulla3139** [Legion2/CorsairLightingProtocol#347]
**Describe the problem**
A clear and concise description of your problem.

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Board: [e.g. Arduino Leonardo]
 - Device: [e.g. Lighting Node PRO]
 - Version of IDE: [e.g. Arduino IDE 1.8.13]
 - Version of CLP: [e.g. 0.15.0]
 - Version of CLP Boards: [e.g. 0.2.0]
 - Sketch: [e.g. RepeatAndScale]

**Code changes**
Did you changed the code of the library or the sketch?

**Comment by Legion2** [comment]
Yes that should be possible
