### ISSUE TITLE
TinyUSB Support for ESP32-S2?

### ISSUE THREAD

**Issue by eroboticdude** [Legion2/CorsairLightingProtocol#349]
I have some esp32-s2 boards arriving soon, and I was curious if using the tinyUSB implementation for esp32 was possible 
(https://github.com/chegewara/esp32-usb-v2)

These boards don't use the USB to TTL converter I believe, so could it be possible to use this library with the existing tinyUSB support this library has? I'll probably do some experimenting myself, but I'm not strong with firmware and library creation. One thing that is promising is the ability to change the hardware definitions and other things. I'm not sure if the library allows use of the USB-C port on the boards, but it would be very nice if it did.

**Comment by Legion2** [comment]
Sorry but I'm not familiar with the tinyUSB implementation and can not help with this question.
