### ISSUE TITLE
Is there any way to add more channels?

### ISSUE THREAD

**Issue by Mate1980** [Legion2/CorsairLightingProtocol#350]
I have 4 Light Wings and two led strips that i can't daisy chain. Is there any way to controll them individualy?

Thanks for your help!

**Comment by Legion2** [comment]
Yeah that is possible, see https://github.com/Legion2/CorsairLightingProtocol/blob/dev/examples/MultipleFans/MultipleFans.ino

**Comment by Mate1980** [comment]
Thanks for the help, it works!

**Comment by Mate1980** [comment]
Thanks for the help, it works!
