### ISSUE TITLE
more than 2 channels

### ISSUE THREAD

**Issue by saeedbs** [Legion2/CorsairLightingProtocol#353]
is it possible to have more than 2 channels? 
or somehow have 2 corsair virtual device on 1 Arduino?  something like lighting node pro and commander pro on 1 arduino at same time  so we get 2 channel from each

**Comment by Legion2** [comment]
No, but you can split a channel to use multiple led devices on one channel, see https://github.com/Legion2/CorsairLightingProtocol/blob/dev/examples/MultipleFans/MultipleFans.ino

**Comment by saeedbs** [comment]
I know that but more channels could be nice

**Comment by Legion2** [comment]
iCUE only supports two channels.

**Comment by saeedbs** [comment]
what if I use openrgb and not icue ? is it possible to define more channel? will openrgb detect them as corsair device but with more channels?

**Comment by Legion2** [comment]
The number of channels are defined by the device types, and Corsair has only defined device types with up to two channels. There is no way to tell openrgb the number of available channels via the USB protocol.
