### ISSUE TITLE
Cannot compile for Arduino Uno 16u2

### ISSUE THREAD

**Issue by cschlisner** [Legion2/CorsairLightingProtocol#354]
**I have followed the guide exactly and cannot compile the project in IDE v2.2.1 or IDE v1.8.18**

I have confirmed Hoodloader2 flashed correctly:
![image](https://github.com/Legion2/CorsairLightingProtocol/assets/3262210/23710927-a321-4c65-9cb1-942356f409ab)
![image](https://github.com/Legion2/CorsairLightingProtocol/assets/3262210/badfa45b-6091-4ba6-91c0-216e4ea6644c)

And I am now trying to follow the install guide here: 
https://github.com/Legion2/CorsairLightingProtocol/wiki/How-to-use-on-Arduino-Uno-and-Arduino-Mega#upload-the-sketches

And I am getting errors related to HID:
![image](https://github.com/Legion2/CorsairLightingProtocol/assets/3262210/3396cfc3-5ec9-4103-8b0f-063d3d214900)

Even though I have the HID-Project library installed. 

I also was getting a similar error when I tried it in an older IDE Version (1.8.18):
![image](https://github.com/Legion2/CorsairLightingProtocol/assets/3262210/10a9e644-82a9-4786-a0c4-1a2919652504)

Is this even possible?

**Comment by cschlisner** [comment]
I managed to get it to compile and upload by just leaving the board as "arduino Uno" but I doubt that will actually work. I tried proceeding but Step 8 of the installation guide says "select Tools->Device->Lighting Node PRO" 
However this menu does not exist:
![image](https://github.com/Legion2/CorsairLightingProtocol/assets/3262210/16f1b0a7-2304-4d0d-a6c7-d2aedc17b5af)

I got this error when attempting step 10. 
![image](https://github.com/Legion2/CorsairLightingProtocol/assets/3262210/d1a1e351-f6c8-43a9-9f84-98a6d72461e8)

**Comment by Legion2** [comment]
> However this menu does not exist:

Is this screenshot from Arduino IDE 2 or 1? Please only use Arduino IDE 1, I have not tested 2 jet.
