### ISSUE TITLE
Commander pro to 6 argb fans

### ISSUE THREAD

**Issue by JACKAR710** [Legion2/CorsairLightingProtocol#363]
I've been looking through your repository and it's really something. I was wondering if you have any advice on creating a controller that takes the data sent by a channel on the Commander pro, and converts it so that you'd be able to control multiple 3 pin argb devices. This would be very helpful when using signalRGB.

Kind regards,
A fellow embedded fanatic

**Comment by Legion2** [comment]
What do you mean by 3 pin devices? Normal addressable led stripes? Have a look at https://github.com/Legion2/CorsairLightingProtocol/blob/dev/examples%2FMultipleFans%2FMultipleFans.ino. it controls multiple led strips per channel.

**Comment by JACKAR710** [comment]
I read the code and I couldn't really figure out how the avr board is supposed to recieve data from the lighting node (or in my case the commander pro). With 3 pin argb I meant the goto argb connection.

**Comment by Legion2** [comment]
do you know how to use the FastLED library and how to wire the components?
