### ISSUE TITLE
Hardware lightning not working

### ISSUE THREAD

**Issue by Fregoudi** [Legion2/CorsairLightingProtocol#368]
Hardware lighting not working. When I close the icue software or turn off my computer, the towers do not work and the LEDs remain solid. Can you help me?

 - OS: [e.g. Windows 10]
 - Board: [e.g. Arduino Leonardo]
 - Device: [e.g. LT100]
 - Version of IDE: [e.g. Arduino IDE 1.8.57]
 - Version of CLP: [e.g. 0.15.0]
 - Version of CLP Boards: [e.g. 0.3.1]

**Comment by Legion2** [comment]
You need to configure the hardware lighting in iCue before it works. Can you please provide a screenshot of your hardware lighting configuration in icue.

**Comment by Fregoudi** [comment]
I remember doing the configuration before but I guess I didn't. I did what you said and it's working now. I had another question, how do I add a button for on/off operation?

**Comment by Legion2** [comment]
The LS100 examples includes code for on/off button https://github.com/Legion2/CorsairLightingProtocol/blob/dev/examples%2FLS100%2FLS100.ino#L23

**Comment by Fregoudi** [comment]
How do I add it to lt100?

**Comment by Legion2** [comment]
You have to write the code yourself 😉

**Comment by Fregoudi** [comment]
thanks
