### ISSUE TITLE
PI PICO RP2040 as Lightning Node Core

### ISSUE THREAD

**Issue by Huzaifa17681** [Legion2/CorsairLightingProtocol#375]
I apologize if this matter has already been addressed elsewhere, but I'd like to quickly ask if I would be able to use the Pi Pico RP2040 as a node core. Would the wiring be the same but with more data pins involved? Additionally, I've noticed people facing memory issues. Should I proceed to get the original Pi Pico RP2040 or the 16MB version?

**Comment by Legion2** [comment]
Please have a look at the readme, there is a section on "Create a Lighting Node PRO for a Raspberry Pi Pico with TinyUSB" which explains what you are looking for.

**Comment by Huzaifa17681** [comment]
Thanks <<3
