### ISSUE TITLE
Hardware Lighting Mode: Default mode

### ISSUE THREAD

**Issue by JLIspace** [Legion2/CorsairLightingProtocol#378]
Hey,

I’m using a Arduino Leonardo with a none-addressable LED strip. It works fine with OpenRGB, the only issue is that the rainbow mode starts automatically when my PC is off for ~5 seconds. I don’t want to install iCue, is there a code-option to set the default hardware lighting mode (in my case static black) without iCue?

Thanks in advance!

**Comment by Legion2** [comment]
Yes you can call the API to send a fake command to update the hardware lighting config.
