### ISSUE TITLE
Flickering with scale function enabled , if the arduino is disconnected from icue 

### ISSUE THREAD

**Issue by brazzo97** [Legion2/CorsairLightingProtocol#55]
hi if i enable the scale function on my config to port from 60 to 120 led when i start up the pc so there is no connection with the icue software the rainbow effect goes completly crazy flickering , that doesnt happen if i use the repeat function

**Comment by Legion2** [comment]
I know this is a bug and I'm currently fixing it.

**Comment by Legion2** [comment]
@brazzo97 Thanks for the bug report, do you want to try the fix?

**Comment by brazzo97** [comment]
Thank you , now its working fine , i am making a donation now . 
Really thanks

**Comment by Legion2** [comment]
@brazzo97 Thank you very much for your donation 👍
