### ISSUE TITLE
Add Support for Corsair Lighting Node CORE

### ISSUE THREAD

**Issue by Legion2** [Legion2/CorsairLightingProtocol#58]
Make it possible to create a Corsair Lighting Node CORE with this library.
Needed information:
- [x] USB PID
- [x] USB Product Name
- [x] Supported commands

**Comment by Legion2** [comment]
I found the ids, there are documented in the [wiki](https://github.com/Legion2/CorsairLightingProtocol/wiki/How-to-use-Corsair-fans-or-other-hardware#rgb-controller).

**Comment by Gannit** [comment]
What would the pinouts be for the node core? There are 6 ports vs the pro's 2 which would be very useful for multiple fans.  
Oh and thanks for the great work.

**Comment by Legion2** [comment]
If you know the type of fans used, you can program the arduino to expose the 6 different pins for each fan, but else the Node CORE has one channel with one pin and you have to create a circuit that chains the fans. The chaining of fans must pass the output data signal of the previous to the next fan.
