### ISSUE TITLE
Fan noise while using PWM on Commander PRO

### ISSUE THREAD

**Issue by Gannit** [Legion2/CorsairLightingProtocol#75]
I have built a circuit for the commander PRO and I am using the PWM signal to drive an N channel MOSFET to run the 12v fans pulsing the negatice rail. I use the same technique on my 3D printers.  However anything less then a 100% duty cycle spins the fans ok but makes the fans noisy where you can here the PWM pulsing from the fan. like a background buzzing. I have tried multiple types of fans. 

I Tried changing the fan update rate from 500 to a lower value but it didnt seem to make any difference.

**Comment by Legion2** [comment]
which pins do you use for the fan pwm signal?

**Comment by Legion2** [comment]
Also which board do you use? The PWM timings depend on the boards used, I only tested it with Pro Micro.

**Comment by Gannit** [comment]
I connected the fans to pins 5, 6 and 9 guided by the code in the examples Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Leon Kiefer <notifications@github.com> Date: 30/11/2019  13:42  (GMT+00:00) To: Legion2/CorsairLightingProtocol <CorsairLightingProtocol@noreply.github.com> Cc: Gannit <lesliekite7@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Legion2/CorsairLightingProtocol] Fan noise while using PWM on Commander PRO (#75) which pins do you use for the fan pwm signal?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Legion2/CorsairLightingProtocol/issues/75?email_source=notifications\u0026email_token=AN5CK4SGMIITUR4IQ4PFVP3QWJUSZA5CNFSM4JTGTG32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFQHHYI#issuecomment-559969249",
"url": "https://github.com/Legion2/CorsairLightingProtocol/issues/75?email_source=notifications\u0026email_token=AN5CK4SGMIITUR4IQ4PFVP3QWJUSZA5CNFSM4JTGTG32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFQHHYI#issuecomment-559969249",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Gannit** [comment]
Ah I am using a pro micro however not the spark fun version. It could be that. When programming I have to set it as a leonardo as when I choose pro micro, it wont upload. The ones I have here are by keeyees (a Chinese brand I believe)I will get hold of a spark fun board and try with that. Thank you  Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Leon Kiefer <notifications@github.com> Date: 30/11/2019  13:58  (GMT+00:00) To: Legion2/CorsairLightingProtocol <CorsairLightingProtocol@noreply.github.com> Cc: Gannit <lesliekite7@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Legion2/CorsairLightingProtocol] Fan noise while using PWM on Commander PRO (#75) Also which board do you use? The PWM timings depend on the boards used, I only tested it with Pro Micro.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Legion2/CorsairLightingProtocol/issues/75?email_source=notifications\u0026email_token=AN5CK4TGSWSXMIRM5VBPES3QWJWRTA5CNFSM4JTGTG32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFQHV4Q#issuecomment-559971058",
"url": "https://github.com/Legion2/CorsairLightingProtocol/issues/75?email_source=notifications\u0026email_token=AN5CK4TGSWSXMIRM5VBPES3QWJWRTA5CNFSM4JTGTG32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFQHV4Q#issuecomment-559971058",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Legion2** [comment]
@Gannit Did you try with the other board?

**Comment by Gannit** [comment]
I managed to get hold of a full size leonardo and it worked ok.  So I'm guessing it could be the cheap clone arduino causing the issue. Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Leon Kiefer <notifications@github.com> Date: 16/12/2019  18:26  (GMT+00:00) To: Legion2/CorsairLightingProtocol <CorsairLightingProtocol@noreply.github.com> Cc: Gannit <lesliekite7@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [Legion2/CorsairLightingProtocol] Fan noise while using PWM on Commander PRO (#75) @Gannit Did you try with the other board?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Legion2/CorsairLightingProtocol/issues/75?email_source=notifications\u0026email_token=AN5CK4X3S424ZNC2JDOLVDTQY7B37A5CNFSM4JTGTG32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEG7UDXI#issuecomment-566182365",
"url": "https://github.com/Legion2/CorsairLightingProtocol/issues/75?email_source=notifications\u0026email_token=AN5CK4X3S424ZNC2JDOLVDTQY7B37A5CNFSM4JTGTG32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEG7UDXI#issuecomment-566182365",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Legion2** [comment]
Ok i will then close this Issue, if you have any other problem or suggestion, you can open a new one.
