### ISSUE TITLE
LS100, Lagging on whole Setup

### ISSUE THREAD

**Issue by SketchTv** [Legion2/CorsairLightingProtocol#87]
**Some kind package Bug**
When I connect the LS100 (running on Arduino Pro Micro) the whole Setup starts hanging and lagging on some points.

**Comment by Legion2** [comment]
With Setup do you mean the PC? Which version of CLP library did you used?

**Comment by Legion2** [comment]
@SketchTv please provide more information about the problem and the context in which it occurs. Have a look at [bug report template](https://github.com/Legion2/CorsairLightingProtocol/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md) to get an overview of useful information that you should provide.

**Comment by Legion2** [comment]
I'm closing this as it's not clear what is the problem or how to reproduce it.
